<?php
header( 'Content-Type: text/html; charset=UTF-8' );
error_reporting(E_ALL);
//ini_set('memory_limit', '256M');
set_time_limit(0);
ini_set("max_execution_time",0);

$myversion='20150521_0050';
$DATABASE_SIGS = unserialize( base64_decode( 'czoyOToiLi4vc2lncy9kYi1jbGVhbnVwL2RiLXNpZ3MuZGIiOw==' ) );
$ENCODED_SIGS = unserialize( base64_decode( 'czozMDoiLi4vc2lncy9kYi1jbGVhbnVwL2RiLXNpZ3MuZW5jIjs=' ) );
$list_of_option_rows = unserialize( base64_decode( 'YTozOntpOjA7czoxNToid3BfZG9vcmdlbl9jb2RlIjtpOjE7czoxNzoid3BfZG9vcmdlbl9jb25maWciO2k6MjtzOjExOiJ3cF9vcHRpbWl6ZSI7fQ==' ) );
$list_of_spam_links = unserialize( base64_decode( 'YTozNDY6e3M6MTI6IjAtdmlhZ3JhLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTU6IjFnZW5lcmljLWNpYWxpcyI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6IjFwaGFybWFjeXN0b3JlIjtzOjk6InNwYW1fbGluayI7czoxNToiMXN0LXBheWRheWxvYW5zIjtzOjk6InNwYW1fbGluayI7czo1OiIyNDdwaCI7czo5OiJzcGFtX2xpbmsiO3M6MjE6IjI0N3BoYXJtYWNldXRpY2FsLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6ImFic2Nhbm5pbmcuY29tIjtzOjk6InNwYW1fbGluayI7czoxMToiYWNjdXRhbmVidXkiO3M6OToic3BhbV9saW5rIjtzOjE0OiJhY2lhbGlzZm9yc2FsZSI7czo5OiJzcGFtX2xpbmsiO3M6MjU6ImFjb21wbGlhLW9ubGluZS1wcmljZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjI1OiJhY29tcGxpYS1vbmxpbmUtcHJpY2UubmV0IjtzOjk6InNwYW1fbGluayI7czoxNjoiYWN0aXZpdGllc3RhYmxlcyI7czo5OiJzcGFtX2xpbmsiO3M6MzA6ImFkb2JlY3JlYXRpdmVzdWl0ZWRvd25sb2FkLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6ImFsbC1mb3J1bXMuYml6IjtzOjk6InNwYW1fbGluayI7czoyMToiYW1lcmljYW5sYW5kb3duZXIuY29tIjtzOjk6InNwYW1fbGluayI7czoyMjoiYW1lcmljYW5sYW5kb3duZXJzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjE6ImFtZXJpY2FudHJhbnNwb3J0cGVydSI7czo5OiJzcGFtX2xpbmsiO3M6MTM6ImFtZXJpbHlueC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjY6ImFtb3hpbCI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImFtb3hpbC1jaGVhcC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE2OiJhbW94aWwtcGlsbHMubmV0IjtzOjk6InNwYW1fbGluayI7czoxNToiYW1veGlsY2hlYXAubmV0IjtzOjk6InNwYW1fbGluayI7czoxNToiYW1veGlscGhhcm0uY29tIjtzOjk6InNwYW1fbGluayI7czoxNToiYW1veGlscGhhcm0ubmV0IjtzOjk6InNwYW1fbGluayI7czoxNToiYW1veGlscGlsbHMubmV0IjtzOjk6InNwYW1fbGluayI7czoyMDoiYW1waWNpbGxpbi1waGFybS5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJhbXBpY2lsbGluLXBoYXJtLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MjA6ImFtcGljaWxsaW4tcGlsbHMuY29tIjtzOjk6InNwYW1fbGluayI7czoyMDoiYW1waWNpbGxpbi1waWxscy5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE5OiJhbXBpY2lsbGlucGlsbHMuY29tIjtzOjk6InNwYW1fbGluayI7czoxOToiYW1waWNpbGxpbnBpbGxzLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImFudGliaW90aWNzLXNob3AiO3M6OToic3BhbV9saW5rIjtzOjIwOiJhbnRpYmlvdGljcy1zaG9wLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjE6ImFudGliaW90aWNzLXN0b3JlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjE6ImFudGliaW90aWNzb3JkcmVyLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImFwcHJhaXNlZDR5b3UuY29tIjtzOjk6InNwYW1fbGluayI7czoxMzoiYXJhdWpvYWx2YXJleiI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImFyZWx5c2ZyYW5rZW4uY29tIjtzOjk6InNwYW1fbGluayI7czoyNDoiYXJndW1lbnRhdGl2ZWVzc2F5cGFwZXJzIjtzOjk6InNwYW1fbGluayI7czoxOToiYXJvbWF0ZXJhcGlhLmNvbS5wZSI7czo5OiJzcGFtX2xpbmsiO3M6MTk6ImFydGVzLW1hcmNpYWxlcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjI0OiJhdXRvcmVzcG9uZGVyLm1tLXByb2plY3QiO3M6OToic3BhbV9saW5rIjtzOjE0OiJhdmlhZ3JhZm9yc2FsZSI7czo5OiJzcGFtX2xpbmsiO3M6Mjg6ImF2aWFncmFmb3JzYWxlLmNvbWJhc2ljcGlsbHMiO3M6OToic3BhbV9saW5rIjtzOjExOiJiYnV5LWNpYWxpcyI7czo5OiJzcGFtX2xpbmsiO3M6MjY6ImJlYXV0aWZ1bHN1bW1lcm1vcm5pbmcuY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoiYmVzdC1jaWFsaXMtcHJpY2UiO3M6OToic3BhbV9saW5rIjtzOjIyOiJiZXN0YWZmaWxpYXRlbGFuZG1pbmVzIjtzOjk6InNwYW1fbGluayI7czoyMjoiYmVzdGFudGl2aXJ1c3NvZnR3YXJlMSI7czo5OiJzcGFtX2xpbmsiO3M6MjM6ImJlc3RjaGVhcC1jaWFsaXMtb25saW5lIjtzOjk6InNwYW1fbGluayI7czoxNToiYmlrZWNvbGxlY3RpdmVzIjtzOjk6InNwYW1fbGluayI7czoxNDoiYmlrZXJjaGlja3oud3MiO3M6OToic3BhbV9saW5rIjtzOjEwOiJidXkgY2lhbGlzIjtzOjk6InNwYW1fbGluayI7czoxNzoiYnV5LWNoZWFwcC1jaWFsaXMiO3M6OToic3BhbV9saW5rIjtzOjE3OiJidXktY2lhbGlzLW9ubGluZSI7czo5OiJzcGFtX2xpbmsiO3M6MjA6ImJ1eS1jaWFsaXMtb25saW5lLWVkIjtzOjk6InNwYW1fbGluayI7czoxMToiYnV5LWNpYWxpc3MiO3M6OToic3BhbV9saW5rIjtzOjE5OiJidXktY2xvbWlkLW9ubGluZTI0IjtzOjk6InNwYW1fbGluayI7czoyNDoiYnV5LXByb3BlY2lhLW9ubGluZWUuY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoiYnV5TGFzaXhjaGVhcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjI5OiJidXljaGVhcGNpYWdyZXR0ZXNvbmxpbmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjA6ImJ1eWNoZWFwY2lhbGlzb25saW5lIjtzOjk6InNwYW1fbGluayI7czo5OiJidXljaWFsaXMiO3M6OToic3BhbV9saW5rIjtzOjIxOiJidXljeXRvdGVjb25saW5lZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJidXlkaWZsdWNhbmNoZWFwLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImJ1eWRpZmx1Y2Fub25saW5lZSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImJ1eWZsYWd5bGNoZWFwLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImJ1eWZsYWd5bG9ubGluZWUiO3M6OToic3BhbV9saW5rIjtzOjI4OiJidXlnZW5lcmljcHJpbGlneW9ubGluZWUuY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoiYnV5bGFzaXhjaGVhcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJidXlsZXZhcXVpbmNoZWFwLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjA6ImJ1eW5vbHZhZGV4Y2hlYXAuY29tIjtzOjk6InNwYW1fbGluayI7czoyMToiYnV5cHJvc2Nhcm9ubGluZWUuY29tIjtzOjk6InNwYW1fbGluayI7czoyMzoiYnV5cm9sZXhyZXBsaWNhd2F0Y2hlc3MiO3M6OToic3BhbV9saW5rIjtzOjE5OiJidXlzb2Z0Y2lhbGlzb25saW5lIjtzOjk6InNwYW1fbGluayI7czoxMjoiYnV5c3Rlcm9pZHNzIjtzOjk6InNwYW1fbGluayI7czoyMDoiYnV5eGVuaWNhb25saW5lZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE4OiJidXl5cHJvcGVjaWFvbmxpbmUiO3M6OToic3BhbV9saW5rIjtzOjIzOiJidXl6aXRocm9tYXhvb25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImNhbGxpbnNlYXJjaC5jb20iO3M6OToic3BhbV9saW5rIjtzOjE3OiJjYW1hZ3JhLXBoYXJtLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImNhbWFncmEtcGhhcm0ubmV0IjtzOjk6InNwYW1fbGluayI7czoxNjoiY2FtYWdyYWNoZWFwLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImNhbWFncmFjaGVhcC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjI1OiJjYW5hZGlhbi1waGFybWFjeS05MTEuY29tIjtzOjk6InNwYW1fbGluayI7czoyNDoiY2FuYWRpYW4tcGhhcm1hY3ktc3RvcmVzIjtzOjk6InNwYW1fbGluayI7czoxOToiY2FuYWRpYW5waGFybWFjeXdlYiI7czo5OiJzcGFtX2xpbmsiO3M6MTI6ImNhbmRsZXN0b25lcyI7czo5OiJzcGFtX2xpbmsiO3M6MjI6ImNhbmliZWFtaWxsaW9uYWlyZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjEyOiJjYXBlY28uZWR1LnAiO3M6OToic3BhbV9saW5rIjtzOjIxOiJjYXB0YWluZHNndWlkZXNlcnZpY2UiO3M6OToic3BhbV9saW5rIjtzOjE2OiJjYXNleXNjb3JuZXIuY29tIjtzOjk6InNwYW1fbGluayI7czoxNjoiY2FzaHF1aWNrb25saW5lZSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImNjaWFsaXMtcHJpY2Uub3JnIjtzOjk6InNwYW1fbGluayI7czoxMToiY2NpYWxpczIwbWciO3M6OToic3BhbV9saW5rIjtzOjEzOiJjY2lhbGlzb25saW5lIjtzOjk6InNwYW1fbGluayI7czo2OiJjZWZ0aW4iO3M6OToic3BhbV9saW5rIjtzOjE2OiJjaGFtcGFnbmF0MzcuY29tIjtzOjk6InNwYW1fbGluayI7czoxNDoiY2hhbm5lbGtvbGthdGEiO3M6OToic3BhbV9saW5rIjtzOjI3OiJjaGVhcC1jYW5hZGlhbi1waGFybWFjeS5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE3OiJjaGVhcC1jaWFsaXNlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImNoZWFwLWNpYWxpc3MuY29tIjtzOjk6InNwYW1fbGluayI7czoxOToiY2hlYXBwY2lhbGlzLW9ubGluZSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImNoZWFwcGlsbHNvbmxpbmUiO3M6OToic3BhbV9saW5rIjtzOjExOiJjaGVhcHZpYWdyYSI7czo5OiJzcGFtX2xpbmsiO3M6MjM6ImNoZWFwd2VzdGNpZ2FyZXR0ZXMuY29tIjtzOjk6InNwYW1fbGluayI7czoyMToiY2hlY2tjcmVkaXRzY29yZWZmcmVlIjtzOjk6InNwYW1fbGluayI7czoxNToiY2hpY2tuZWdnc3VwcGx5IjtzOjk6InNwYW1fbGluayI7czoyMToiY2hvb3NlZ3JlYXRoZWFsdGguY29tIjtzOjk6InNwYW1fbGluayI7czo5OiJjaWFsaXMtMjAiO3M6OToic3BhbV9saW5rIjtzOjExOiJjaWFsaXMtYmVzdCI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImNpYWxpcy1jYW5hZGEuY29tIjtzOjk6InNwYW1fbGluayI7czoyMToiY2lhbGlzLWdlbmVyaWMtZWQuY29tIjtzOjk6InNwYW1fbGluayI7czoxOToiY2lhbGlzLWdlbmVyaWNzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6ImNpYWxpcy1vbmxpbmUtaXRhbGlhLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MjM6ImNpYWxpcy1vbmxpbmUtcHJpY2UuY29tIjtzOjk6InNwYW1fbGluayI7czoyMzoiY2lhbGlzLW9ubGluZS1wcmljZS5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE4OiJjaWFsaXMtb25saW5lc2FsZXMiO3M6OToic3BhbV9saW5rIjtzOjE1OiJjaWFsaXMtcGFzLWNoZXIiO3M6OToic3BhbV9saW5rIjtzOjE2OiJjaWFsaXMtcGhhcm0uY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoiY2lhbGlzLXBpbGxzcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjEzOiJjaWFsaXMtcHJpY2VlIjtzOjk6InNwYW1fbGluayI7czoxNDoiY2lhbGlzLXByaWNlc3MiO3M6OToic3BhbV9saW5rIjtzOjEyOiJjaWFsaXMtcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjMyOiJjaWFsaXMtd2l0aG91dC1wcmVzY3JpcHRpb25zLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MzM6ImNpYWxpcy13aXRob3V0dC1wcmVzY3JpcHRpb25zLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6NzoiY2lhbGlzMSI7czo5OiJzcGFtX2xpbmsiO3M6NzoiY2lhbGlzYSI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6ImNpYWxpc2NhbmFkYXN0IjtzOjk6InNwYW1fbGluayI7czoxMzoiY2lhbGlzb25saW5lZSI7czo5OiJzcGFtX2xpbmsiO3M6MjA6ImNpYWxpc29ubGluZW5vd2Uub3JnIjtzOjk6InNwYW1fbGluayI7czoxNDoiY2lhbGlzb25saW5lb24iO3M6OToic3BhbV9saW5rIjtzOjE3OiJjaWFsaXNvb25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTM6ImNpYWxpc3ByaWNlYWEiO3M6OToic3BhbV9saW5rIjtzOjEyOiJjaWFsaXNwcmljZWUiO3M6OToic3BhbV9saW5rIjtzOjE2OiJjaWFsaXNzLTIwbWcuY29tIjtzOjk6InNwYW1fbGluayI7czoxODoiY2lhbGlzcy1vbmxpbmUub3JnIjtzOjk6InNwYW1fbGluayI7czoxMzoiY2lhbGlzcy1wcmljZSI7czo5OiJzcGFtX2xpbmsiO3M6MzI6ImNpYWxpc3Mtd2l0aG91dC1wcmVzY3JpcHRpb24uY29tIjtzOjk6InNwYW1fbGluayI7czoyMjoiY2lhbGlzc3VwZXJhY3RpdmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6ODoiY2lwcm8yNGgiO3M6OToic3BhbV9saW5rIjtzOjIxOiJjbGFyaWZ5dGhldHJ1dGhpbmNoaW4iO3M6OToic3BhbV9saW5rIjtzOjIwOiJjbGFzc2ljcGF5ZGF5bG9hbnN1ayI7czo5OiJzcGFtX2xpbmsiO3M6MTM6ImNsaW5lc2l0ZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjEzOiJjbG9taWRvbmxpbmVlIjtzOjk6InNwYW1fbGluayI7czoyMjoiY29tcHJhcmUtY2lhbGlzLW9ubGluZSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImNvbXB1dGVyc29mdHdhcmVlIjtzOjk6InNwYW1fbGluayI7czoxMzoiY29tdW5pY2FyLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MTE6ImNvbmdyZXNzZmF4IjtzOjk6InNwYW1fbGluayI7czoxNDoiY29uZ3Jlc3NmYXguY28iO3M6OToic3BhbV9saW5rIjtzOjg6ImNwcGwub3JnIjtzOjk6InNwYW1fbGluayI7czoyMDoiY3JlZGl0bm9wcm9ibGVtcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjE1OiJjcmVlazJjb2FzdC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIzOiJjdXBpZG9pbnRlcm5hY2lvbmFsLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6OToiY3d0cmFuc2xsIjtzOjk6InNwYW1fbGluayI7czoyMDoiY3l0b3RlY2J1eW9ubGluZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE3OiJkYWNvbXBsaWFzYWxlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTI6ImRhbGVtYXJrLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImRjaWFsaXNmb3JzYWxlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImRjaWFsaXNmb3JzYWxlLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MTU6ImRlYnRzZXR0bGVtZW50dCI7czo5OiJzcGFtX2xpbmsiO3M6MTU6ImRlbHRhc29uZW9ubGluZSI7czo5OiJzcGFtX2xpbmsiO3M6MTU6ImRpcGxvbWFmYWtlcy5jbyI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImRsZXZpdHJhb25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6ImRvbXlhc3NpZ25tZW50b25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImRvdWdsYXNtaXNxdWl0YS5jIjtzOjk6InNwYW1fbGluayI7czoyMToiZG93bmxvYWRzb2Z0d2FyZWUuY29tIjtzOjk6InNwYW1fbGluayI7czoxMzoiZG93bm1vcnRnYWdlcyI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImR6aXRocm9tYXhzYnV5LmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImUtb25saW5lY2lhbGlzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImUtb25saW5lY2lhbGlzLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MjE6ImUtcGhhcm1hY3ktb25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImUtdmlhZ3Jhb25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImUtdmlhZ3Jhb25saW5lLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MTI6ImVsY2FycmV0ZS5jbCI7czo5OiJzcGFtX2xpbmsiO3M6MTM6ImVtYmFsYWplc3BlcnUiO3M6OToic3BhbV9saW5rIjtzOjE1OiJlbm9wcmVzY3JpcHRpb24iO3M6OToic3BhbV9saW5rIjtzOjI3OiJlbm9wcmVzY3JpcHRpb24tbGV2aXRyYS5jb20iO3M6OToic3BhbV9saW5rIjtzOjI3OiJlbm9wcmVzY3JpcHRpb24tbGV2aXRyYS5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE1OiJlbnpvc3Jlc3RhdXJhbnQiO3M6OToic3BhbV9saW5rIjtzOjI4OiJlc3NheXByb2Zlc3Npb25hbHdyaXRpbmcuY29tIjtzOjk6InNwYW1fbGluayI7czoyNDoiZXNzYXl3cml0aW5nc3NlcnZpY2UuY29tIjtzOjk6InNwYW1fbGluayI7czoyMToiZXNzYXl3cml0aW5nc3NlcnZpY2VzIjtzOjk6InNwYW1fbGluayI7czoxNjoiZXh0cmVtZXZhbHVlaG9zdCI7czo5OiJzcGFtX2xpbmsiO3M6MjE6ImZhc3QtcGF5ZGF5LWxvYW5zLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MjM6ImZlbWFsZXZpYWdyYWJ1eXNhbGUuY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoiZmxhZ3lsb25saW5lZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE1OiJmb3JtYXRpb25zdHVkaW8iO3M6OToic3BhbV9saW5rIjtzOjE2OiJmcmVlLXRyYWZmaWNib29tIjtzOjk6InNwYW1fbGluayI7czoxNToiZ2VuZXJpYy1jaWFsaXNzIjtzOjk6InNwYW1fbGluayI7czoxOToiZ2VuZXJpYy1lZC1waGFybWFjeSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImdlbmVyaWNjaWFsaXNmYXN0IjtzOjk6InNwYW1fbGluayI7czoxMDoiZ2V0cnhwaWxscyI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6ImdldHJ4cGlsbHMuY29tIjtzOjk6InNwYW1fbGluayI7czozNToiZ2dlbmVyaWMtY2lhbGlzLW5vLXByZXNjcmlwdGlvbi5jb20iO3M6OToic3BhbV9saW5rIjtzOjE3OiJncmVhdC1sZXZpdHJhLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6ImhlYWx0aGNhcmV4eXouY29tIjtzOjk6InNwYW1fbGluayI7czoxMjoiaG90c3BpbGwuY29tIjtzOjk6InNwYW1fbGluayI7czoxODoiaG93dG91c2VteWlwYWQuY29tIjtzOjk6InNwYW1fbGluayI7czoyMjoiaXBob25lc3B5c29mdHdhcmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6ImpvYW5iZWF1bGlldS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE4OiJqdXJpc3BydWRlbmNpYWNpdmkiO3M6OToic3BhbV9saW5rIjtzOjE3OiJrYW1hZ3Jhc29yZGVyLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6NzoibGV2aXRyYSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6Imxldml0cmEtb25saW5lLXByaWNlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6Imxldml0cmEtb25saW5lLXByaWNlLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MTM6ImxpYmVydHlkaW5pbmciO3M6OToic3BhbV9saW5rIjtzOjE2OiJsaWZlNHN1Y2Nlc3MubmV0IjtzOjk6InNwYW1fbGluayI7czoxMjoibG9hbnNzb25saW5lIjtzOjk6InNwYW1fbGluayI7czoxMToibG9zZWV3ZWlnaHQiO3M6OToic3BhbV9saW5rIjtzOjE4OiJtYWtlbW9uZXlpbnRlcm5ldHQiO3M6OToic3BhbV9saW5rIjtzOjE3OiJtaXJhY2xlLXByZWduYW5jeSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6Im1sbXN1Y2Nlc3Nmb3JtdWxhIjtzOjk6InNwYW1fbGluayI7czoyMToibWxtc3VjY2Vzc2Zvcm11bGEuY29tIjtzOjk6InNwYW1fbGluayI7czoyMzoibW9uZXlncmFtbG9jYXRpb25zLmluZm8iO3M6OToic3BhbV9saW5rIjtzOjI0OiJtb3ZpZWRvd25sb2FkbWFuYWdlci5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJtdXNjbGUtdHJhaW5pbmcuaW5mbyI7czo5OiJzcGFtX2xpbmsiO3M6MjY6Im15LWFmZmlsaWF0ZXMtcHJvZ3JhbXMuY29tIjtzOjk6InNwYW1fbGluayI7czoyNToibmFzYWwtcG9seXAtdHJlYXRtZW50LmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTE6Im5ldG1lZHguY29tIjtzOjk6InNwYW1fbGluayI7czoyNzoibm9uLXByZXNjcmlwdGlvbi1jaWFsaXMuY29tIjtzOjk6InNwYW1fbGluayI7czoxODoibm9ucHJlc2NyaXB0aW9ubWVkIjtzOjk6InNwYW1fbGluayI7czoxNDoibm9wcmVzY3JpcHRpb24iO3M6OToic3BhbV9saW5rIjtzOjI0OiJvbmVkb2xsYXIubW0tcHJvamVjdC5jb20iO3M6OToic3BhbV9saW5rIjtzOjE2OiJvbmVuZXRjZW50ZXIuY29tIjtzOjk6InNwYW1fbGluayI7czoxMzoib25saW5lIGNhc2lubyI7czo5OiJzcGFtX2xpbmsiO3M6MTk6Im9ubGluZS1jYXNoLWFkdmFuY2UiO3M6OToic3BhbV9saW5rIjtzOjIyOiJvbmxpbmUtcGhhcm1hY3ktc3QuY29tIjtzOjk6InNwYW1fbGluayI7czoxMjoib25saW5lLXBpbGxzIjtzOjk6InNwYW1fbGluayI7czoxMToib25saW5lLXByZXMiO3M6OToic3BhbV9saW5rIjtzOjI2OiJvbmxpbmUtcHJlc2NyaXB0aW9ubWVkLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MjM6Im9ubGluZWFjb21wbGlhY2hlYXAuY29tIjtzOjk6InNwYW1fbGluayI7czoyMzoib25saW5lYWNvbXBsaWFjaGVhcC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjIxOiJvbmxpbmVjaWFsaXNjaGVhcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJvbmxpbmVjaWFsaXNjaGVhcC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjIyOiJvbmxpbmVsZXZpdHJhY2hlYXAuY29tIjtzOjk6InNwYW1fbGluayI7czoyMjoib25saW5lbGV2aXRyYWNoZWFwLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MTk6Im9ubGluZW9yZGVyY2lhbGlzdWsiO3M6OToic3BhbV9saW5rIjtzOjI0OiJvbmxpbmVwYXlkYXlsb2FuLTI0aC5jb20iO3M6OToic3BhbV9saW5rIjtzOjE0OiJvbmxpbmVwaGFybWFjeSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6Im9ubGluZXBoYXJtYWN5LWRydWdzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTk6Im9ubGluZXBpbGxzc2hvcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJvbmxpbmV2aWFncmFjaGVhcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJvbmxpbmV2aWFncmFjaGVhcC5uZXQiO3M6OToic3BhbV9saW5rIjtzOjIwOiJvcmRlci1jaWFsaXMtb25saW5lcSI7czo5OiJzcGFtX2xpbmsiO3M6MTM6Im9yZGVyLWNpYWxpc3MiO3M6OToic3BhbV9saW5rIjtzOjE2OiJvcmRlcmNoZWFwY2lhbGlzIjtzOjk6InNwYW1fbGluayI7czoxNzoib3JkZXJyLWNpYWxpcy5vcmciO3M6OToic3BhbV9saW5rIjtzOjIyOiJvdmVyNTBsb3Npbmd3ZWlnaHQuY29tIjtzOjk6InNwYW1fbGluayI7czoxMzoicGFwZXJ3cml0aW5nMSI7czo5OiJzcGFtX2xpbmsiO3M6MTc6InBhc3Npb25vZmxpZmUubmV0IjtzOjk6InNwYW1fbGluayI7czoxMjoicGF5ZGF5IGxvYW5zIjtzOjk6InNwYW1fbGluayI7czoyMjoicGVhbXBpY2lsbGlub25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6NjoicGhhcm0tIjtzOjk6InNwYW1fbGluayI7czoxODoicGhhcm0tcHJlc2NyaXB0aW9uIjtzOjk6InNwYW1fbGluayI7czoxOToicGhhcm1hY2llLS1lbi1saWduZSI7czo5OiJzcGFtX2xpbmsiO3M6Mjk6InBoYXJtYWNpZS1lbi1saWduZS1jaWFsaXMub3JnIjtzOjk6InNwYW1fbGluayI7czoxNToicGhhcm1hY3ktY2hlYXBzIjtzOjk6InNwYW1fbGluayI7czoxNjoicGhhcm1hY3ktcGlsbDI0NyI7czo5OiJzcGFtX2xpbmsiO3M6MjA6InBoYXJtYWN5LXBpbGwzNjUuY29tIjtzOjk6InNwYW1fbGluayI7czoxNjoicGlsbHMtY2lhbGlzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6Mjc6InBsb2NpYS1jaWFsaXMtdGFkYWxhZmlsLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTE6InByb3ByYW5vbG9sIjtzOjk6InNwYW1fbGluayI7czoxMDoicWdhcy5jby51ayI7czo5OiJzcGFtX2xpbmsiO3M6MTI6InF1aWNrIHBheWRheSI7czo5OiJzcGFtX2xpbmsiO3M6MTM6InJ4LXByaWNlcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjE4OiJzYnV5aW5nLWNpYWxpcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjE4OiJzYnV5aW5nLWNpYWxpcy5uZXQiO3M6OToic3BhbV9saW5rIjtzOjE0OiJzY2xvbWlkYnV5LmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTk6InNkb3h5Y3ljbGluZWJ1eS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE0OiJzZWVhdmlzaW9uLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTU6InNoYXJlLXZpZGVvLmluZiI7czo5OiJzcGFtX2xpbmsiO3M6MTU6InNpbHZlcndhdGVyY2FmZSI7czo5OiJzcGFtX2xpbmsiO3M6MjA6InNvZnR2aWFncmFvbmxpbmUuY29tIjtzOjk6InNwYW1fbGluayI7czoyMDoic3Byb3BlY2lhLW9ubGluZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJzcHJvcGVjaWEtb25saW5lLm5ldCI7czo5OiJzcGFtX2xpbmsiO3M6MjU6InNweS1waG9uZS1zb2Z0d2FyZS1vbmxpbmUiO3M6OToic3BhbV9saW5rIjtzOjE2OiJzdGFydC1zdWNjZXNzLXVwIjtzOjk6InNwYW1fbGluayI7czoxNToic3ZpYWdyYXJidXkuY29tIjtzOjk6InNwYW1fbGluayI7czo5OiJ0NGhiLmluZm8iO3M6OToic3BhbV9saW5rIjtzOjE5OiJ0YWtlYWZyZWVjcnVpc2UuY29tIjtzOjk6InNwYW1fbGluayI7czoxNzoidGFzdHlvbmxpbmVjYXNpbm8iO3M6OToic3BhbV9saW5rIjtzOjIwOiJ0ZWFtYnVpbGRuZXR3b3JrLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MTU6InRoZWNoZWFwLWNpYWxpcyI7czo5OiJzcGFtX2xpbmsiO3M6MTU6InRvcGxldml0cmFndWlkZSI7czo5OiJzcGFtX2xpbmsiO3M6MTY6InVnY3MuY2FsdGVjaC5lZHUiO3M6OToic3BhbV9saW5rIjtzOjE3OiJ1bml0ZWRyZXRlay5jby51ayI7czo5OiJzcGFtX2xpbmsiO3M6MTk6InVzLWNhZC1waGFybWFjeS5jb20iO3M6OToic3BhbV9saW5rIjtzOjE0OiJ2ZW5kaXRhLWNpYWxpcyI7czo5OiJzcGFtX2xpbmsiO3M6NjoidmVybW94IjtzOjk6InNwYW1fbGluayI7czo2OiJ2aWFncmEiO3M6OToic3BhbV9saW5rIjtzOjIzOiJ2aWFncmEtb25saW5lLXByaWNlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjM6InZpYWdyYS1vbmxpbmUtcHJpY2UubmV0IjtzOjk6InNwYW1fbGluayI7czoxMzoidmlhZ3JhZW5saWduZSI7czo5OiJzcGFtX2xpbmsiO3M6MTE6InZpYWdyYWVzLmVzIjtzOjk6InNwYW1fbGluayI7czoxMzoidmlhZ3JhZm9yc2FsZSI7czo5OiJzcGFtX2xpbmsiO3M6MjM6InZpYWdyYW5vcHJlc2NyaXB0aW9uLTFzIjtzOjk6InNwYW1fbGluayI7czoxNjoidmljaWFsaXNhYnV5LmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTE6IndlYmVtZWQuY29tIjtzOjk6InNwYW1fbGluayI7czozNDoid2VzdGVybnVuaW9uLWNvdW50cnktbG9jYXRpb25zLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjY6Indlc3Rlcm51bmlvbi1sb2NhdGlvbnMuY29tIjtzOjk6InNwYW1fbGluayI7czoxODoid2hlcmV0b2dldHN0ZXJvaWRzIjtzOjk6InNwYW1fbGluayI7czoyMDoid2ljaGl0YWJyb2FkYmFuZC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJ3b21lbi1oZWFsdGgtc2hvcC5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJ3cHJvcGVjaWFub25saW5lLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjM6IndyaXRlbXllbmdsaXNocGFwZXIub3JnIjtzOjk6InNwYW1fbGluayI7czoyMzoid3JpdGluZ3NlcnZpY2VzNHlvdS5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJ3d3cuYW1waGktZmVzdGl2YWwuZGUiO3M6OToic3BhbV9saW5rIjtzOjI3OiJ3d3cuaGVhbHRoZml0bmVzc3JlbWVkeS5jb20iO3M6OToic3BhbV9saW5rIjtzOjMyOiJ3d3cubXktYmVhdXR5LWhlYWx0aC1maXRuZXNzLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6Ind3dy5zY29yZS1sb3Vpc3ZpbGxlLm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MjI6Ind3dy51bHRyYWRhcmtyYWRpby5jb20iO3M6OToic3BhbV9saW5rIjtzOjIxOiJ3d3cudmlhZ3JhLW91dGxldC5jb20iO3M6OToic3BhbV9saW5rIjtzOjE2OiJ3d3cueWFsZWFhc2Eub3JnIjtzOjk6InNwYW1fbGluayI7czoyMjoieGVub3BoYXJtYWNvcGhpbGlhLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTk6InhtaWNyb2dhbWluZ2Nhc2lub3MiO3M6OToic3BhbV9saW5rIjtzOjE2OiJ5b3Utc3RhcnQtdXAuY29tIjtzOjk6InNwYW1fbGluayI7czoyMToieW91cmRpc2NvdW50NGZyZWUuY29tIjtzOjk6InNwYW1fbGluayI7czo2OiJ6b2xvZnQiO3M6OToic3BhbV9saW5rIjtzOjI4OiJjaGVzdGVyZmllbGRjaWdhcmV0dGVzNHUub3JnIjtzOjk6InNwYW1fbGluayI7czoyMjoid3JpdGVhbmVzc2F5Zm9ybWVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MTg6ImFkb2Jlc29mdHdhcmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjU6ImFkb2JlYWNyb2JhdGRvd25sb2FkZC5jb20iO3M6OToic3BhbV9saW5rIjtzOjI2OiJibGFja2JlcnJ5c3B5c29mdHdhcmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6ImJ1eWNpZ2FyZXR0ZXNvbmxpbmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MzE6ImJlc3QtZXNzYXktd3JpdGluZy1zZXJ2aWNlcy5jb20iO3M6OToic3BhbV9saW5rIjtzOjI4OiJteS1iZWF1dHktaGVhbHRoLWZpdG5lc3MuY29tIjtzOjk6InNwYW1fbGluayI7czoyNDoiYWRvYmVhY3JvYmF0c29mdHdhcmUuY29tIjtzOjk6InNwYW1fbGluayI7czoyNToiZ29vZGFudGl2aXJ1c3NvZnR3YXJlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6Mjg6InRoZWJlc3RhbnRpdmlydXNzb2Z0d2FyZS5uZXQiO3M6OToic3BhbV9saW5rIjtzOjI3OiJ0aGViZXN0Y29tcHV0ZXJzb2Z0d2FyZS5jb20iO3M6OToic3BhbV9saW5rIjtzOjIwOiJkb3dubG9hZGFkb2JlY3M2Lm9yZyI7czo5OiJzcGFtX2xpbmsiO3M6MjQ6ImVsbHBob25lc3B5c29mdHdhcmVlLmNvbSI7czo5OiJzcGFtX2xpbmsiO3M6MjU6InBheXNvbWVvbmV0b2RvbXllc3NheS5jb20iO3M6OToic3BhbV9saW5rIjtzOjI4OiJiZXN0ZXNzYXl3cml0aW5nc2VydmljZWUuY29tIjtzOjk6InNwYW1fbGluayI7czo3OiJ0YWRhZmlsIjtzOjk6InNwYW1fbGluayI7czo3OiJuaXpvcmFsIjtzOjk6InNwYW1fbGluayI7czo3OiJrYW1hcmdhIjtzOjk6InNwYW1fbGluayI7czoyNDoiYXJlLW1lZHMtZnJvbS1pbmRpYS1zYWZlIjtzOjk6InNwYW1fbGluayI7czozMDoiY2lhbGlzLWNhbmFkaWFuLW5vLXByZXNjaXB0aW9uIjtzOjk6InNwYW1fbGluayI7czoyNDoid2hlcmUtY2FuLWktYnV5LXBoZW5ncmVuIjtzOjk6InNwYW1fbGluayI7czo4OiJjaWFsaXMtMCI7czo5OiJzcGFtX2xpbmsiO3M6MTI6ImNoZWFwLWNsb21pZCI7czo5OiJzcGFtX2xpbmsiO3M6MTQ6InRhZGFsYWZpbC0yMG1nIjtzOjk6InNwYW1fbGluayI7czoxNDoidGFkYWxhZmlsIDIwbWciO3M6OToic3BhbV9saW5rIjtzOjE1OiJ4ZW5pY2FsLXNoaXBwZXIiO3M6OToic3BhbV9saW5rIjt9' ) );
$list_of_regex = unserialize( base64_decode( 'YTo2OTp7czoyNDoiPCEtLSB+fnNwb25zb3J+fiAtLT48ZGl2IjtzOjQ5OiJAPC4tLSAuLnNwb25zb3IuLiAtLT5bXn5dKjwuLS0gfn5zcG9uc29yZWR+fiAtLT5AIjtzOjE0OiJyb3NhLXRlbWEuaW5mbyI7czo0MjoiQDxzY3JpcHRbXjxdKnJvc2EtdGVtYS5pbmZvW148XSo8LnNjcmlwdD5AIjtzOjIxOiJmdW5jdGlvbiBwNmU5MGY1NDYwOTciO3M6NDk6IkA8c2NyaXB0W148XSpmdW5jdGlvbiBwNmU5MGY1NDYwOTdbXjxdKjwuc2NyaXB0PkAiO3M6MTgwOiJkb2N1bWVudC53cml0ZSh1bmVzY2FwZSgnJTNDJTczJTYzJTcyJTY5JTcwJTc0JTIwJTczJTcyJTYzJTNEJTIyJTY4JTc0JTc0JTcwJTNBJTJGJTJGJTZBJTczJTJEJTZGJTJEJTY0JTY2JTc5JTcxJTY3JTc1JTJFJTYzJTdBJTJFJTYzJTYzJTJGJTMzJTM5JTIyJTNFJTNDJTJGJTczJTYzJTcyJTY5JTcwJTc0JTNFJykiO3M6MTg1OiJAZG9jdW1lbnQud3JpdGVcKHVuZXNjYXBlXCgnJTNDJTczJTYzJTcyJTY5JTcwJTc0JTIwJTczJTcyJTYzJTNEJTIyJTY4JTc0JTc0JTcwJTNBJTJGJTJGJTZBJTczJTJEJTZGJTJEJTY0JTY2JTc5JTcxJTY3JTc1JTJFJTYzJTdBJTJFJTYzJTYzJTJGJTMzJTM5JTIyJTNFJTNDJTJGJTczJTYzJTcyJTY5JTcwJTc0JTNFJ1wpQCI7czo0NToiPHNjcmlwdCBzcmM9Imh0dHA6Ly9hZS5hd2F1ZS5jb20vNyI+PC9zY3JpcHQ+IjtzOjUxOiJAPHNjcmlwdCBzcmM9Imh0dHA6XC9cL2FlLmF3YXVlLmNvbVwvNyI+PFwvc2NyaXB0PkAiO3M6OTg6IjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Imh0dHA6Ly9yb3NhLXRlbWEuaW5mby9kZmk4MjNocy5qcz8wLjQyNDE0NDMxMDU3OTE2OSI+PC9zY3JpcHQ+IjtzOjEwNToiQDxzY3JpcHQgdHlwZT0idGV4dFwvamF2YXNjcmlwdCIgc3JjPSJodHRwOlwvXC9yb3NhLXRlbWEuaW5mb1wvZGZpODIzaHMuanM/MC40MjQxNDQzMTA1NzkxNjkiPjxcL3NjcmlwdD5AIjtzOjQ2OiI8c2NyaXB0IHNyYz0iaHR0cDovL2llLmVyYWNvdS5jb20vMyI+PC9zY3JpcHQ+IjtzOjUyOiJAPHNjcmlwdCBzcmM9Imh0dHA6XC9cL2llLmVyYWNvdS5jb21cLzMiPjxcL3NjcmlwdD5AIjtzOjQ1OiI8c2NyaXB0IHNyYz0iaHR0cDovL2FvLmV1dWF3LmNvbS85Ij48L3NjcmlwdD4iO3M6NTE6IkA8c2NyaXB0IHNyYz0iaHR0cDpcL1wvYW8uZXV1YXcuY29tXC85Ij48XC9zY3JpcHQ+QCI7czo0NjoiPHNjcmlwdCBzcmM9Imh0dHA6Ly91ZS5vZWFvdS5jb20vMzEiPjwvc2NyaXB0PiI7czo1MjoiQDxzY3JpcHQgc3JjPSJodHRwOlwvXC91ZS5vZWFvdS5jb21cLzMxIj48XC9zY3JpcHQ+QCI7czo0NDoiPHNjcmlwdCBzcmM9Imh0dHA6Ly9hZWFhZWEuY29tL291Ij48L3NjcmlwdD4iO3M6NTA6IkA8c2NyaXB0IHNyYz0iaHR0cDpcL1wvYWVhYWVhLmNvbVwvb3UiPjxcL3NjcmlwdD5AIjtzOjQ0OiI8c2NyaXB0IHNyYz0iaHR0cDovL3NlY3JlZS5jb20vcmUiPjwvc2NyaXB0PiI7czo1MDoiQDxzY3JpcHQgc3JjPSJodHRwOlwvXC9zZWNyZWUuY29tXC9yZSI+PFwvc2NyaXB0PkAiO3M6NDQ6IjxzY3JpcHQgc3JjPSJodHRwOi8vdW9hdWVyLmNvbS9zaSI+PC9zY3JpcHQ+IjtzOjUwOiJAPHNjcmlwdCBzcmM9Imh0dHA6XC9cL3VvYXVlci5jb21cL3NpIj48XC9zY3JpcHQ+QCI7czo0NDoiPHNjcmlwdCBzcmM9Imh0dHA6Ly9vZW9vZWEuY29tL3ZlIj48L3NjcmlwdD4iO3M6NTA6IkA8c2NyaXB0IHNyYz0iaHR0cDpcL1wvb2Vvb2VhLmNvbVwvdmUiPjxcL3NjcmlwdD5AIjtzOjQ1OiI8c2NyaXB0IHNyYz0iaHR0cDovL3NlY29uZW8uY29tL29uIj48L3NjcmlwdD4iO3M6NTE6IkA8c2NyaXB0IHNyYz0iaHR0cDpcL1wvc2Vjb25lby5jb21cL29uIj48XC9zY3JpcHQ+QCI7czo0NDoiPHNjcmlwdCBzcmM9Imh0dHA6Ly9zZWNvd28uY29tL3dvIj48L3NjcmlwdD4iO3M6NTA6IkA8c2NyaXB0IHNyYz0iaHR0cDpcL1wvc2Vjb3dvLmNvbVwvd28iPjxcL3NjcmlwdD5AIjtzOjQ0OiI8c2NyaXB0IHNyYz0iaHR0cDovL291cm91ZS5jb20vc2UiPjwvc2NyaXB0PiI7czo1MDoiQDxzY3JpcHQgc3JjPSJodHRwOlwvXC9vdXJvdWUuY29tXC9zZSI+PFwvc2NyaXB0PkAiO3M6NDg6InNyYz0iaHR0cDovL2J3aW5wb2tlcjI0LmNvbS9jbGljazcuanMiPjwvc2NyaXB0PiI7czo2NDoiQDxzY3JpcHQgW14+XSo/c3JjPSJodHRwOi4uYndpbnBva2VyMjQuY29tLmNsaWNrNy5qcyI+PC5zY3JpcHQ+QCI7czo4MjoiPGg1PjxzY3JpcHQgc3JjPWh0dHA6Ly9wdXJwbGUuc21hcnRlbmVyZ3ltb2RlbC5jb20vanMvanF1ZXJ5Lm1pbi5qcz48L3NjcmlwdD48L2g1PiI7czo5MDoiQDxoNT48c2NyaXB0IHNyYz1odHRwOlwvXC9wdXJwbGUuc21hcnRlbmVyZ3ltb2RlbC5jb21cL2pzXC9qcXVlcnkubWluLmpzPjxcL3NjcmlwdD48XC9oNT5AIjtzOjc4OiI8aDU+PHNjcmlwdCBzcmM9aHR0cDovL2hnLnNtYXJ0ZW5lcmd5bW9kZWwuY29tL2pzL2pxdWVyeS5taW4uanM+PC9zY3JpcHQ+PC9oNT4iO3M6ODY6IkA8aDU+PHNjcmlwdCBzcmM9aHR0cDpcL1wvaGcuc21hcnRlbmVyZ3ltb2RlbC5jb21cL2pzXC9qcXVlcnkubWluLmpzPjxcL3NjcmlwdD48XC9oNT5AIjtzOjc0OiI8aDU+PHNjcmlwdCBzcmM9aHR0cDovL2FxdWEua2FyZW5lZ3Jlbi5jb20vanMvanF1ZXJ5Lm1pbi5qcz48L3NjcmlwdD48L2g1PiI7czo4MjoiQDxoNT48c2NyaXB0IHNyYz1odHRwOlwvXC9hcXVhLmthcmVuZWdyZW4uY29tXC9qc1wvanF1ZXJ5Lm1pbi5qcz48XC9zY3JpcHQ+PFwvaDU+QCI7czo3MzoiPGg1PjxzY3JpcHQgc3JjPWh0dHA6Ly9lcWUudG9vbGJhcmluYy5jb20vanMvanF1ZXJ5Lm1pbi5qcz48L3NjcmlwdD48L2g1PiI7czo4MToiQDxoNT48c2NyaXB0IHNyYz1odHRwOlwvXC9lcWUudG9vbGJhcmluYy5jb21cL2pzXC9qcXVlcnkubWluLmpzPjxcL3NjcmlwdD48XC9oNT5AIjtzOjc4OiI8aDU+PHNjcmlwdCBzcmM9aHR0cDovL29vLnNtYXJ0ZW5lcmd5bW9kZWwuY29tL2pzL2pxdWVyeS5taW4uanM+PC9zY3JpcHQ+PC9oNT4iO3M6ODY6IkA8aDU+PHNjcmlwdCBzcmM9aHR0cDpcL1wvb28uc21hcnRlbmVyZ3ltb2RlbC5jb21cL2pzXC9qcXVlcnkubWluLmpzPjxcL3NjcmlwdD48XC9oNT5AIjtzOjcxOiI8c2NyaXB0IHNyYz0iaHR0cDovL3dlbGNvbWV0b3RoZWdsb2JhbGlzb3JnLmNvbS9qcy5waHA/a2s9MjYiPjwvc2NyaXB0PiI7czo3NjoiQDxzY3JpcHQgc3JjPSJodHRwOi9cL3dlbGNvbWV0b3RoZWdsb2JhbGlzb3JnLmNvbVwvanMucGhwP2trPTI2Ij48XC9zY3JpcHQ+QCI7czo3MzoiPHNjcmlwdCBzcmM9Imh0dHA6Ly9nbG9iYWxwb3dlcmluZ2dhdGhlcmluZ29uLmNvbS9sbC5waHA/a2s9MTYiPjwvc2NyaXB0PiI7czo3OToiQDxzY3JpcHQgc3JjPSJodHRwOlwvXC9nbG9iYWxwb3dlcmluZ2dhdGhlcmluZ29uLmNvbVwvbGwucGhwP2trPTE2Ij48XC9zY3JpcHQ+QCI7czo3NDoiPGg1PjxzY3JpcHQgc3JjPWh0dHA6Ly9seDViLnRvb2xiYXJpbmMuY29tL2pzL2pxdWVyeS5taW4uanM+PC9zY3JpcHQ+PC9oNT4iO3M6ODA6IkA8aDU+PHNjcmlwdCBzcmM9aHR0cDovL2x4NWIudG9vbGJhcmluYy5jb21cL2pzXC9qcXVlcnkubWluLmpzPjxcL3NjcmlwdD48XC9oNT5AIjtzOjUzOiI8c2NyaXB0IHNyYz0iaHR0cDovL2luamouaWdub3JlbGlzdC5jb20vMTQiPjwvc2NyaXB0PiI7czo1NzoiQDxzY3JpcHQgc3JjPSJodHRwOi8vaW5qai5pZ25vcmVsaXN0LmNvbVwvMTQiPjxcL3NjcmlwdD5AIjtzOjc2OiI8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSJodHRwOi8vaW5qai5pZ25vcmVsaXN0LmNvbS8xNCI+PC9zY3JpcHQ+IjtzOjgzOiJAPHNjcmlwdCB0eXBlPSJ0ZXh0XC9qYXZhc2NyaXB0IiBzcmM9Imh0dHA6XC9cL2luamouaWdub3JlbGlzdC5jb21cLzE0Ij48XC9zY3JpcHQ+QCI7czo5NjoiPGlmcmFtZSBzcmM9Imh0dHA6Ly9nb29nbGUtcGluZ2luZ3MuY29tL2luLmNnaT9kZWZhdWx0IiBoZWlnaHQ9MSB3aWR0aD0xIGZyYW1lYm9yZGVyPTA+PC9pZnJhbWU+IjtzOjEwMjoiQDxpZnJhbWUgc3JjPSJodHRwOlwvXC9nb29nbGUtcGluZ2luZ3MuY29tXC9pbi5jZ2k/ZGVmYXVsdCIgaGVpZ2h0PTEgd2lkdGg9MSBmcmFtZWJvcmRlcj0wPjxcL2lmcmFtZT5AIjtzOjEwNzoiPGlmcmFtZSBzcmM9Imh0dHA6Ly9zMTY5MDcwODA1Lm9ubGluZWhvbWUudXMvMjAwOC8wMS9nby5waHA/c2lkPTYiIGhlaWdodD0xIHdpZHRoPTEgZnJhbWVib3JkZXI9MD48L2lmcmFtZT4iO3M6MTE1OiJAPGlmcmFtZSBzcmM9Imh0dHA6XC9cL3MxNjkwNzA4MDUub25saW5laG9tZS51c1wvMjAwOFwvMDFcL2dvLnBocD9zaWQ9NiIgaGVpZ2h0PTEgd2lkdGg9MSBmcmFtZWJvcmRlcj0wPjxcL2lmcmFtZT5AIjtzOjY3OiI8c2NyaXB0IHNyYz0iaHR0cDovL3N3ZWVwc3Rha2VzYW5kY29udGVzdHNkby5jb20vcG1nLnBocCI+PC9zY3JpcHQ+IjtzOjczOiJAPHNjcmlwdCBzcmM9Imh0dHA6XC9cL3N3ZWVwc3Rha2VzYW5kY29udGVzdHNkby5jb21cL3BtZy5waHAiPjxcL3NjcmlwdD5AIjtzOjcwOiI8c2NyaXB0IHNyYz0iaHR0cDovL3N3ZWVwc3Rha2VzYW5kY29udGVzdHNkby5jb20vbmwucGhwP3A9ZCI+PC9zY3JpcHQ+IjtzOjc2OiJAPHNjcmlwdCBzcmM9Imh0dHA6XC9cL3N3ZWVwc3Rha2VzYW5kY29udGVzdHNkby5jb21cL25sLnBocD9wPWQiPjxcL3NjcmlwdD5AIjtzOjkyOiI8aWZyYW1lIHNyYz1odHRwOi8vNjEuMTMyLjc1LjcxL2lmcmFtZS93cC1zdGF0cy5waHAgd2lkdGg9MSBoZWlnaHQ9MSBmcmFtZWJvcmRlcj0wPjwvaWZyYW1lPiI7czo5OToiQDxpZnJhbWUgc3JjPWh0dHA6XC9cLzYxLjEzMi43NS43MVwvaWZyYW1lXC93cC1zdGF0cy5waHAgd2lkdGg9MSBoZWlnaHQ9MSBmcmFtZWJvcmRlcj0wPjxcL2lmcmFtZT5AIjtzOjgxOiI8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSJodHRwOi8vYXNhdW5pcmcuY29tLmJyL2pzLzBkYXkucGhwIj48L3NjcmlwdD4iO3M6ODk6IkA8c2NyaXB0IHR5cGU9InRleHRcL2phdmFzY3JpcHQiIHNyYz0iaHR0cDpcL1wvYXNhdW5pcmcuY29tLmJyXC9qc1wvMGRheS5waHAiPjxcL3NjcmlwdD5AIjtzOjgzOiI8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSJodHRwOi8vZGVueWJvbmZhbnRlLmNvbS9hcHAvTWVudS5waHAiPjwvc2NyaXB0PiI7czo5MToiQDxzY3JpcHQgdHlwZT0idGV4dFwvamF2YXNjcmlwdCIgc3JjPSJodHRwOlwvXC9kZW55Ym9uZmFudGUuY29tXC9hcHBcL01lbnUucGhwIj48XC9zY3JpcHQ+QCI7czo4MDoiPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIHNyYz0iaHR0cDovL2xpZy1saW1wLmNvbS5ici9yZWJvdHMucGhwIj48L3NjcmlwdD4iO3M6ODc6IkA8c2NyaXB0IHR5cGU9InRleHRcL2phdmFzY3JpcHQiIHNyYz0iaHR0cDpcL1wvbGlnLWxpbXAuY29tLmJyXC9yZWJvdHMucGhwIj48XC9zY3JpcHQ+QCI7czo1MjoiPHNjcmlwdCBzcmM9Imh0dHA6Ly9cJGRvbWFpbi9sbC5waHA/a2s9MTEiPjwvc2NyaXB0PiI7czo1ODoiQDxzY3JpcHQgc3JjPSJodHRwOlwvXC9cJGRvbWFpblwvbGwucGhwP2trPTExIj48XC9zY3JpcHQ+QCI7czoxMTA6IjxpZnJhbWUgc3JjPSJodHRwOi8vc2hhbmdhY3VwdW5jdHVyZS5vc2EucGwvc2hvd3RocmVhZC5waHA/dD01Nzg1MjQ2NCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZnJhbWVib3JkZXI9IjAiIC8+IjtzOjExNjoiQDxpZnJhbWUgc3JjPSJodHRwOlwvXC9zaGFuZ2FjdXB1bmN0dXJlLm9zYS5wbFwvc2hvd3RocmVhZC5waHA/dD01Nzg1MjQ2NCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZnJhbWVib3JkZXI9IjAiIFwvPkAiO3M6MTc0OiI8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSIvd3AtY29udGVudC8tLXBsdWdpbnMub2xkL3dwLXBvcHVwLXNjaGVkdWxlci9lZGl0b3IvanNjcmlwdHMvdGlueV9tY2UvcGx1Z2lucy9pbmxpbmVwb3B1cHMvc2tpbnMvY2xlYXJsb29rczIvYWN0aW9uX3JlcXVlc3QucGhwIj48L3NjcmlwdD4iO3M6MTg5OiJAPHNjcmlwdCB0eXBlPSJ0ZXh0XC9qYXZhc2NyaXB0IiBzcmM9Ilwvd3AtY29udGVudFwvLS1wbHVnaW5zLm9sZFwvd3AtcG9wdXAtc2NoZWR1bGVyXC9lZGl0b3JcL2pzY3JpcHRzXC90aW55X21jZVwvcGx1Z2luc1wvaW5saW5lcG9wdXBzXC9za2luc1wvY2xlYXJsb29rczJcL2FjdGlvbl9yZXF1ZXN0LnBocCI+PFwvc2NyaXB0PkAiO3M6MTcyOiI8c2NyaXB0PmFsZXJ0KCdoYWNrZWQgYnkgSG1laTcnKTwvc2NyaXB0PjxoMT5oYWNrZWQgYnkgSG1laTc8YnIgLz48L2gxPjxkaXYgc3R5bGU9YmFja2dyb3VuZC1jb2xvcjpibGFjazs+PGJyIC8+PGgxPjxmb250IGNvbG9yPWN5YW4+aGFja2VkIGJ5IEhtZWk3PC9mb250PjwvaDE+PGJyIC8+PC9kaXY+IjtzOjE4NDoiQDxzY3JpcHQ+YWxlcnRcKCdoYWNrZWQgYnkgSG1laTcnXCk8XC9zY3JpcHQ+PGgxPmhhY2tlZCBieSBIbWVpNzxiciBcLz48XC9oMT48ZGl2IHN0eWxlPWJhY2tncm91bmQtY29sb3I6YmxhY2s7PjxiciBcLz48aDE+PGZvbnQgY29sb3I9Y3lhbj5oYWNrZWQgYnkgSG1laTc8XC9mb250PjxcL2gxPjxiciBcLz48XC9kaXY+QCI7czo2OiJ2aWFncmEiO3M6OTU6IkA8cFxzc3R5bGU9ImhlaWdodDogMHB0O3dpZHRoOiAwcHQ7cG9zaXRpb246IGFic29sdXRlO292ZXJmbG93OiBhdXRvOyI+Lio/dmlhZ3JhLio/W148XSo8XC9wPkBpIjtzOjE4OiJ0by1nZXQtZXgtYmFjay5vcmciO3M6Njc6IkA8ZGl2IHN0eWxlPSJkaXNwbGF5OiBub25lIj4uKj90by1nZXQtZXgtYmFjay5vcmcvLio/W148XSo8XC9kaXY+QGkiO3M6OToidmFyIF8wMTE9IjtzOjg5OiJAPHNjcmlwdCBsYW5ndWFnZT0iamF2YXNjcmlwdCIgdHlwZT0idGV4dFwvamF2YXNjcmlwdCI+dmFyIF8wMTEuKj9fMDExXClcKVwpOzxcL3NjcmlwdD5AaSI7czoxOToicmtfY3p4VjFkdjFVVGZFcmRReSI7czo3NzoiQDwhLS0gcmtfY3p4VjFkdjFVVGZFcmRReS5bMC05XSAtLT4uKj88IS0tIFwvcmtfY3p4VjFkdjFVVGZFcmRReS5bMC05XSAtLT5AaXMiO3M6MTM6InZpYWdyYWtvcGVubmwiO3M6MzE6IkB2aWFncmFrb3Blbm5sLW5sLXZpYWdyYS1zb2Z0QGkiO3M6OToiY2lhbGlzbWVkIjtzOjI2OiJAY2lhbGlzbWVkLio/Y2lhbGlzXHM1bWdAaSI7czo5OiJnb29nbGUuanMiO3M6NjU6IkA8c2NyaXB0IHR5cGU9WyJ8J10uKjkxXC4yMzlcLjE1XC42MVwvZ29vZ2xlXC5qc1tePF0qPFwvc2NyaXB0PkBpIjtzOjE0OiJkb2N1bWVudC53cml0ZSI7czo4MToiQDxzY3JpcHQgbGFuZ3VhZ2U9ImphdmFzY3JpcHQiPlxzZG9jdW1lbnRcLndyaXRlXCguKj8lM0MlMjElNDQlNEYuKj88XC9zY3JpcHQ+QGlzIjtzOjg6ImVyZWN0aWxlIjtzOjEyMjoiQDxkaXYgaWQ9Ii4qPyIgc3R5bGU9InBvc2l0aW9uOiBhYnNvbHV0ZTsgdG9wOiAtXGR7Myx9cHg7IGxlZnQ6IC1cZHszLH1weDsgd2lkdGg6IFsyLi40XVxkezJ9cHg7Ij4uKj9lcmVjdGlsZS4qPzxcL2Rpdj5AaXMiO3M6MTY6InZpYWdyYSBvdmVybmlnaHQiO3M6MTI4OiJAPGRpdlxzKnN0eWxlLi5wb3NpdGlvbjphYnNvbHV0ZTtccypsZWZ0Oi1bMC05XXs0LH1weDtccyp0b3A6LVswLTldezQsfXB4Oy4+KFxzKlx3K1tePl0rYSBocmVmW14+XSs+XHMqXHcrW14+XSthPil7MSx9W14+XStkaXY+QCI7czoyMDoiPGRpdiBzdHlsZT0iZGlzcGxheToiO3M6NDA6IkA8ZGl2IHN0eWxlPSJkaXNwbGF5OlxzKj9ub25lIj48XC9kaXY+QGkiO3M6Mjc6IjxkaXYgc3R5bGU9ImRpc3BsYXk6IG5vbmUiPiI7czo1ODoiQDxkaXYgc3R5bGU9ImRpc3BsYXk6IG5vbmUiPi4qP2Zhcm1hY2lhMjQuKj9bXjxdKjxcL2Rpdj5AaSI7czozMjoiLS0+PGEgc3R5bGU9ImRpc3BsYXk6bm9uZTsiIGhyZWYiO3M6Njk6IkA8XCEtLShcd3syM30pLS0+PGEgc3R5bGU9ImRpc3BsYXk6bm9uZTsiIGhyZWY9Ii4rPzxcL2E+PFwhLS1cL1wxLS0+QCI7czozNzoiPGRpdiBzdHlsZT0icG9zaXRpb246YWJzb2x1dGU7IGxlZnQ6LSI7czoxNDQ6IkA8ZGl2IHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgbGVmdDotWzAtOV17NCx9cHg7XHMqdG9wOi1bMC05XXs0LH1weDtbXj5dKz4uXHMqXHcrW14+XSsoPGEgaHJlZltePl0rPi5ccypcdytbXj5dKzwuYT4uXHMqXHcrW148XSspezMsfTwuZGl2PkBpcyI7czo3NjoiPGRpdiBzdHlsZT0icG9zaXRpb246YWJzb2x1dGU7ZmlsdGVyOmFscGhhKG9wYWNpdHk9MCk7b3BhY2l0eTowLjAwMTt6LWluZGV4OiI7czoxMDI6IjxkaXYgc3R5bGU9LnBvc2l0aW9uOmFic29sdXRlO2ZpbHRlcjphbHBoYS5vcGFjaXR5PTAuO29wYWNpdHk6MC4wMDE7ei1pbmRleDpcZCs7Lj48YSBocmVmPS4rP2E+PFwvZGl2PiI7czozNDoiZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmlubmVySFRNTCI7czoyMzA6IkA8c2NyaXB0PmRvY3VtZW50XC5kb2N1bWVudEVsZW1lbnRcLmlubmVySFRNTFxzPVxzdW5lc2NhcGVcKCclNDglNjElNjMlNGIlNjUlNDQlMjAlNDIlNzklMjAlNDQlNzIlMmUlNTMlNDglNDElMzYlNDglMjAlN2MlMjAlNDYlNzUlNjMlNmIlMjAlNDElNmMlNmMlMjAlNTMlNjklNzQlNjUlMjAlM2QlMjklMjAlNWIlMjAlNDclMzIlM2ElMjAlNGIlMzElNTYlMzMlNmUlMjAlNWQnXCk7PFwvc2NyaXB0PkBpIjtzOjc6ImRnc2dzZGciO3M6NDE6IkA8c2NyaXB0Pi4qP2Rnc2dzZGcuKj9ldmFsLio/PFwvc2NyaXB0PkBpIjtzOjIzOiJkb2N1bWVudC53cml0ZSh1bmVzY2FwZSI7czoyMzk6IkBkb2N1bWVudC53cml0ZVwoW1xzXSp1bmVzY2FwZVwoW1xzXSouJyUzQyUyMSU0NCU0RiU0MyU1NCU1OS4qPyUyQyUyMCUyMiU2OCU3NCU3NCU3MCUzQSUyRiUyRltcdyVdKj8lMkYlNjclNkYlNkYlNjclNkMlNjUlMkUlNkElNzMlMjIlMjklMEElMjAuKj8lNjglNjUlNjElNjQlM0UlMEElMEElM0MlNjIlNkYlNjQlNzklM0UlMEElM0MlMkYlNjIlNkYlNjQlNzklM0UlMEElM0MlMkYlNjglNzQlNkQlNkMlM0UuXClcKTtAIjtzOjExOiJ6cDg0OTc1ODZycSI7czo1ODoiQDxkaXYgc3R5bGU9ImRpc3BsYXk6W1xzXSo/bm9uZVs7XSo/Ij56cDg0OTc1ODZycTxcL2Rpdj5AaSI7czozMjoiPGRpdiBzdHlsZT0iZGlzcGxheTpub25lIj48L2Rpdj4iO3M6NDc6IkA8ZGl2IHN0eWxlPSJkaXNwbGF5Oltcc10qP25vbmVbO10qPyI+PFwvZGl2PkBpIjtzOjEwOiI5MDkxOTY4Mzc2IjtzOjk2OiJAPHNjcmlwdCBsYW5ndWFnZS4qPzkwOTE5NjgzNzYuKj9TdHJpbmcuZnJvbUNoYXJDb2RlLio/ZG9jdW1lbnQud3JpdGUuKj9kbm5Jbml0XChcKTs8XC9zY3JpcHQ+QGkiO3M6MjI6IkdxZ1NzZE1WTjU4QlVlUTl6SFZFclMiO3M6NzI6IkA8ZGl2IGlkPSJHcWdTc2RNVk41OEJVZVE5ekhWRXJTIiBzdHlsZT0icG9zaXRpb246IGFic29sdXRlOy4qPz48XC9kaXY+QCI7czoxOToiYXNydi1hLmFrYW1haWhkLm5ldCI7czo3MToiQDxzY3JpcHQgaWQ9Ilx3KyIgc3JjPSIuLmFzcnYtYS5ha2FtYWloZC5uZXQuc2QvXGQrL1xkK1wuanMiPjwvc2NyaXB0PkAiO3M6MTcwOiJjaHIoNjQpLmNocigxMDEpLmNocigxMTgpLmNocig5NykuY2hyKDEwOCkuY2hyKDQwKS5jaHIoOTgpLmNocig5NykuY2hyKDExNSkuY2hyKDEwMSkuY2hyKDU0KS5jaHIoNTIpLmNocig5NSkuY2hyKDEwMCkuY2hyKDEwMSkuY2hyKDk5KS5jaHIoMTExKS5jaHIoMTAwKS5jaHIoMTAxKS5jaHIoNDApLiI7czoyMTM6IkBce1wkXHtcJFx3K1xzKj1bXjtdK2NoclwoNjRcKVwuY2hyXCgxMDFcKVwuY2hyXCgxMThcKVwuY2hyXCg5N1wpXC5jaHJcKDEwOFwpXC5jaHJcKDQwXClcLmNoclwoOThcKVwuY2hyXCg5N1wpXC5jaHJcKDExNVwpXC5jaHJcKDEwMVwpXC5jaHJcKDU0XClcLmNoclwoNTJcKVwuY2hyXCg5NVwpXC5jaHJcKDEwMFwpXC5jaHJcKDEwMVwpW147XStcfVx9KFx7XCRcdytcfSk/QCI7czo5NDoiY3VtZW50LmNyZWF0ZUVsZW1lbnQoImRpdiIpO2VsLmlubmVySFRNTD0iJiM4MjsmIzEwMTsmIzEwMjsmIzEwMTsmIzExNDsmIzEwMTsmIzExMDsmIzk5OyYjMTAxOyI7czo5MjoiQDxzY3JpcHQ+ZWw9ZG8uKj9jdW1lbnQuY3JlYXRlRWxlbWVudC4uZGl2Li47ZWwuaW5uZXJIVE1MPSImIzgyOyYjMTAxOy4rP2VcKHNcKTs8XC9zY3JpcHQ+QHMiO3M6MTc6Ijt9ZG9jdW1lbnQud3JpdGUoIjtzOjEzMToiQDxzY3JpcHQgW14+XSs+dmFyXHMqW14+XStkb2N1bWVudC53cml0ZVxzKi4uPC5ccypcK1xzKlthLXpdXFtbMC05XVxdXCsuXHMqLlwrW2Etel1cW1swLTldXF1cKy4+W14+XStbYS16XVxbWzAtOV1cXVteO10rOzwuc2NyaXB0PkAiO3M6MTI6Ij1AJF9DT09LSUVbIiI7czo2NjoiQFwkXHcrPVxAXCRfQ09PS0lFXFsuXHcrLi47XHMqaWZbXlxAXStcQFwkX0NPT0tJRVtePl0rcGhwaW5mby4uO0BpIjtzOjc6InN0cnRyKCQiO3M6MjA3OiJAXCRcd3sxLDJ9XHMqPVxzKidbMC05YS1mXXszMn0nO1xzKlwkXHd7Miw4fVxzKj1ccyonXFMrJztccypcJFx3ezIsOH1ccyo9XHMqJ1xTKyc7XHMqXCRcd3syLDh9XHMqPVxzKidcUysnO1xzKlwkXHd7MSw4fVxzKj1ccyonLi4uJy5zdWJzdHJcKFteXCldKz9cKTtccypcJFx3ezIsOH1ccyo9XHMqcHJlZ19yZXBsYWNlXChcJFteO10rP3N0cnRyXChbXjtdKz87QHMiO3M6MzI6IjoiIiwnY2VudGVyT25TY3JvbGwnOiBmYWxzZX0pO30pIjtzOjYxOiJAIiIsLmNlbnRlck9uU2Nyb2xsLjogZmFsc2UuLjsuLlxzKjwuc2NyaXB0Pi4rPzxzY3JpcHQ+XChce0BzIjtzOjEyOiI9PSIpLCIuIil9fXsiO3M6NTc6IkBce1wkXHtcJFx3Kz1bXixdKyxcJFx3K1woLlx3Kz09LlwpLC5cLi5cKVx9XH1ce1wkXHcrXH1AcyI7fQ==' ) );
$list_of_search = unserialize( base64_decode( 'YTozOTp7czo1OiJldmFsKCI7czoxMToic2VhcmNoX29ubHkiO3M6ODoic3lzdGVtKCciO3M6MTE6InNlYXJjaF9vbmx5IjtzOjE1OiJkb2N1bWVudC53cml0ZSgiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjEzOiJwcmVnX3JlcGxhY2UoIjtzOjExOiJzZWFyY2hfb25seSI7czo3OiJhc3NlcnQoIjtzOjExOiJzZWFyY2hfb25seSI7czo1OiJIbWVpNyI7czoxMToic2VhcmNoX29ubHkiO3M6MTA6ImJ1eSBjaWFsaXMiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjg6ImxldmFxdWluIjtzOjExOiJzZWFyY2hfb25seSI7czo4OiJlcmVjdGlsZSI7czoxMToic2VhcmNoX29ubHkiO3M6Mjc6IjxkaXYgc3R5bGU9ImRpc3BsYXk6IG5vbmUiPiI7czoxMToic2VhcmNoX29ubHkiO3M6NzoiaGFuZ2JhZyI7czoxMToic2VhcmNoX29ubHkiO3M6NToicm9sZXgiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjY6ImNhc2lubyI7czoxMToic2VhcmNoX29ubHkiO3M6OToiY2lhbGlzbWVkIjtzOjExOiJzZWFyY2hfb25seSI7czo2OiJhcmdhaXYiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjY6InNpbGFpYyI7czoxMToic2VhcmNoX29ubHkiO3M6ODoiZWxpdGNlcmUiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjk6ImVjbmV0b3BtaSI7czoxMToic2VhcmNoX29ubHkiO3M6ODoieWNhbXJhaHAiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjY6InlhZHlhcCI7czoxMToic2VhcmNoX29ubHkiO3M6MTQ6ImV0aXJ3LnRuZW11Y29kIjtzOjExOiJzZWFyY2hfb25seSI7czo2OiI0NmVzYWIiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjEyOiJlY2FscGVyX2dlcnAiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjk6ImV0YWxmbml6ZyI7czoxMToic2VhcmNoX29ubHkiO3M6MTE6ImFsX2tpX3NoZWxsIjtzOjExOiJzZWFyY2hfb25seSI7czozNjoiZGl2IHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgbGVmdDotIjtzOjExOiJzZWFyY2hfb25seSI7czozNzoiZGl2IHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgbGVmdDogLSI7czoxMToic2VhcmNoX29ubHkiO3M6MzI6IiBzdHlsZT0icG9zaXRpb246YWJzb2x1dGU7bGVmdDotIjtzOjExOiJzZWFyY2hfb25seSI7czozNjoiZGl2IHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgdG9wOiAtIjtzOjExOiJzZWFyY2hfb25seSI7czozNToiZGl2IHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgdG9wOi0iO3M6MTE6InNlYXJjaF9vbmx5IjtzOjM3OiJkaXYgc3R5bGU9InBvc2l0aW9uOiBhYnNvbHV0ZTsgbGVmdDotIjtzOjExOiJzZWFyY2hfb25seSI7czozODoiZGl2IHN0eWxlPSJwb3NpdGlvbjogYWJzb2x1dGU7IGxlZnQ6IC0iO3M6MTE6InNlYXJjaF9vbmx5IjtzOjM3OiJkaXYgc3R5bGU9InBvc2l0aW9uOiBhYnNvbHV0ZTsgdG9wOiAtIjtzOjExOiJzZWFyY2hfb25seSI7czozNjoiZGl2IHN0eWxlPSJwb3NpdGlvbjogYWJzb2x1dGU7IHRvcDotIjtzOjExOiJzZWFyY2hfb25seSI7czo1MToiZGl2IHN0eWxlPSJwb3NpdGlvbjogYWJzb2x1dGU7IGJvdHRvbTogMHB4OyBsZWZ0OiAtIjtzOjExOiJzZWFyY2hfb25seSI7czo1MDoiPSBwcmVnX3JlcGxhY2UoJGFzLCBzdHJ0cigkdmJnLCAkeG1sLCAkeG1sMiksICdjc3MiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjE4OiI6Ijwvc2NyaXB0PjxzY3JpcHQiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjE4OiI6Ijwvc2NyaXB0PjxpZnJhbWUiO3M6MTE6InNlYXJjaF9vbmx5IjtzOjM3OiIgaGVpZ2h0PSIwIiBmcmFtZWJvcmRlcj0iMCI+PC9pZnJhbWU+IjtzOjExOiJzZWFyY2hfb25seSI7fQ==' ) );
//KEEP EMPTY
//KEEP EMPTY
//KEEP EMPTY
//KEEP EMPTY
//KEEP EMPTY

define( 'DS', DIRECTORY_SEPARATOR );
define( 'QUARANTINE_FOLDER', '.'.DS.'.sucuriquarantine' );
define( 'BACKUP_APPENDIX', '_sucuridbbackup.' );
define( 'SUCURI_KEY', 'kduhgop32lkj' );

echo '<pre>';
echo "Sucuri Database Cleanup v0.0.2\n\n";

/* If running via terminal. */
if( !isset($_SERVER['REMOTE_ADDR']) && isset($_SERVER['SHELL']) ) {
    parse_str(implode('&', array_slice($argv, 1)), $_GET);
}

// auto remove sucuri scripts
if(!isset($_GET['srun']))
{
    @unlink('sucuri-cleanup.php');
    @unlink('sucuri-version-check.php');
    @unlink('sucuri-db-cleanup.php');
    @unlink('sucuri_db_clean.php');
    @unlink('sucuri_listcleaned.php');
    @unlink(__FILE__);
    exit(0);
}

//create sucuri_db_clean.php
if (isset($_GET['dbconfig'])) {
    if (isset($_POST['createconfig'])) {
        if (!isset($_POST['dbname']) || !isset($_POST['dbuser'])  || !isset($_POST['dbpass'])  || !isset($_POST['dbhost'])) {
            exit(1);
        }
        $contents = "<?php

define( 'DB_NAME', '" . $_POST['dbname']. "' );
define( 'DB_USER', '" . $_POST['dbuser']. "' );
define( 'DB_PASSWORD', '" . $_POST['dbpass']. "' );
define( 'DB_HOST', '" . $_POST['dbhost']. "' ) );

?>";

        $result = file_put_contents('sucuri_db_clean.php', $contents);

        if($result) {
            echo 'Successfully stored file: sucuri_db_clean.php';
            exit(1);
        }

        echo 'Unable to store file: sucuri_db_clean.php';
        exit(1);
    }
    echo "Setup sucuri_db_clean.php with custom DB credentials (WARNING: THIS WILL OVERRIDE ANY CURRENT FILE):\n";
    echo '<form method="post" name="addconfig" action="">';

    echo '<input type="hidden" name="createconfig" value="myconfig" />';

    echo 'Database name:'."\t".'<input type="text" name="dbname" value="">'."\n";
    echo 'Username:'."\t".'<input type="text" name="dbuser" value="">'."\n";
    echo 'Password:'."\t".'<input type="text" name="dbpass" value="">'."\n";
    echo 'Host:'."\t\t".'<input type="text" name="dbhost" value="">'."\n";
    echo '<input type="submit" class="greenbutton-small" name="submit" value="Save file" />';

    echo '</form>';

    exit(1);
}

$WPCONFIG = NULL;
$CMS = '';
$config_func = '';
$CMSes = array(
    'sucuri_db_clean.php' => array( 'sucuri_db_clean.php', 'get_wp_config' ),
    'includes/config.php' => array( 'vBulletin', 'get_vb_config' ),
    'configuration.php'   => array( 'Joomla', 'get_joomla_config' ),
    'wp-config.php'       => array( 'Wordpress', 'get_wp_config' ),
    '../wp-config.php'    => array( 'Wordpress', 'get_wp_config' ),
    'sites/default/settings.php'  => array( 'Drupal', 'get_drupal_config' )
);

/* Reading configuration options. */
foreach ( $CMSes as $file => $CMS_array )
{
    if ( !is_readable( $file ) )
    {
        continue;
    }

    echo "{$CMS_array[0]} detected! Config file: $file\n";
    $WPCONFIG = file( $file );
    $CMS = $CMS_array[0];
    $config_func = $CMS_array[1];
    break;
}

if ( NULL === $WPCONFIG )
{
    echo "ERROR: Unable to complete. Missing config file\n";
    exit(1);
}

/* read DB config from the config file */

$DBHOST = '';
$DBUSER = '';
$DBPASS = '';
$DBDB = '';
$DBPREFIX = '';

foreach ( $WPCONFIG as $line )
{
    call_user_func( $config_func, $line );
}

/* Connecting to DB. */
$link = @mysql_connect($DBHOST,$DBUSER,$DBPASS);
if( $link === FALSE ) {
    die('Could not connect to database: ' . mysql_error());
}

if ( '' == $DBHOST
  || '' == $DBUSER
  || '' == $DBDB
)
{
    die('Could not connect to database, no config file found!');
}

echo "\nINFO:Connected successfully to MYSQL\n";
mysql_select_db($DBDB, $link);

mysql_query( "SET NAMES 'utf8'" );

/* Print out file contents */
if(isset($_GET['seefile']) && preg_match("/^[a-zA-Z0-9=]*$/", $_GET['seefile']))
{
    $filename = base64_decode($_GET['seefile']);
    $isBackupFile = false;
    $updated = false;
    $file2 = '';

    if ( false !== strpos( $filename, QUARANTINE_FOLDER . DS ) )
    {
        $isBackupFile = true;
    }

    $file2 = file_get_contents( $filename );

    $file2 = encrypt( $file2, SUCURI_KEY );

    echo( "File: " . htmlspecialchars( $filename ) . " &nbsp; " );


    echo('<pre style="height: 89%">');
    echo('<form method="post" style="height:100%">');
    echo('<textarea name="file_content" style="margin: 2px; height: 90%; width: 100%;">');
    echo(htmlspecialchars($file2));
    echo('</textarea>');
    echo('</form>');
    echo('</pre>');
    exit(0);
}

// restore database
if ( isset( $_GET['restore'] ) )
{
    $file = $_GET['restore'];

    //check is file, if file restore it, if empty, give options
    if ( empty( $file ) )
    {
        if ( isset( $_GET['date'] ) )
        {
            $_GET['date'] = intval( $_GET['date'] );

            if ( $_GET['date'] <= 0 || $_GET['date'] > time() )
            {
                $_GET['date'] = time();
            }
        }

        //get all latest backup files
        $backupFiles = get_all_backup_files();

        echo("Listing all backup files: \n\n");

        $backslashFix = '';
        if ( '\\' == DS ) //fix for backslash literal
        {
            $backslashFix = '\\';
        }

        $backupPattern = '@' . QUARANTINE_FOLDER . $backslashFix . DS .'(.*?)' . BACKUP_APPENDIX . '([0-9]*)@';
        $matches = null;
        $linkPattern = '<a href="%s" target="_blank">%s</a>';

        foreach ( $backupFiles as $backupFile )
        {
            preg_match( $backupPattern, $backupFile, $matches);
            $file = './' . htmlspecialchars( $matches[1] );
            $date = @date('Y-m-d H:i:s', $matches[2]);
            $restoreLink = '?srun&restore=' . base64_encode($file) . "&version={$matches[2]}";
            $seeFileLink = '?srun&seefile=' . base64_encode($backupFile);
            echo( "File: $backupFile - date: $date " . sprintf( $linkPattern, $seeFileLink, 'View' ) .
                ' ' .  sprintf($linkPattern, $restoreLink, 'Restore' ) . "\n" );
        }
    }
    else
    {

        $backups = array();

        $file = base64_decode($file);

        $appendix = '*';

        if ( isset( $_GET['version'] ) )
        {
            $appendix = intval($_GET['version']);
        }

        //restore given file
        $backupFilePattern = QUARANTINE_FOLDER . DS . $file . BACKUP_APPENDIX . $appendix;
        $matchingBackups = glob($backupFilePattern);

        if ( !is_array( $matchingBackups ) || 0 == count ( $matchingBackups ) )
        {
            echo( 'ERROR: Backup file not found. Cannot restore.' );
            exit(0);
        }

        rsort($matchingBackups);
        $backupFile = $matchingBackups[0];

        if ( restore_backup( $backupFile ) )
        {
            echo( 'OK: Restoring DB from ' . htmlspecialchars( $backupFile ) . " backup file\n" );
        }
        else
        {
            echo( 'ERROR: Restoring DB from ' . htmlspecialchars( $backupFile ) . " backup file FAILED!!\n" );
        }
    }
    exit(0);
}

// get all tables
$all_tables = array();
$dbresult = mysql_query('show tables', $link);

// Testing $dbresult mysql_query()
if( $dbresult === FALSE ) {
    echo "\nERROR: Unable to get table information, please use &dbconfig for custom settings";
    exit(0);
}

while($row = mysql_fetch_row($dbresult)) {
    if ( empty( $DBPREFIX ) || false !== strpos( $row[0], $DBPREFIX ) )
    {
        $all_tables[] = $row[0];
    }
}

// show database tables
if( isset($_GET['showtables']) ) {
    echo "\n------- Database Tables -------\n";
    print_r($all_tables);
    echo "\n-------------------------------\n";
    echo implode( ',', $all_tables );
    exit(1);
}

// get all columns

$all_tables_columns=array();

foreach($all_tables as $table) {
    $sql="SHOW COLUMNS FROM `$table`";
    $result = mysql_query($sql) or die("$link-> $sql -- ".mysql_error());
    $columns=array();
    while ($row = mysql_fetch_assoc($result)) {
        $type=$row['Type'];
        $pos=strpos($type,"(");
        if($pos!==false){
            $type=substr($type,0,$pos);
        }
        $columns[]=array($row['Field'],$type);
    }
    $all_tables_columns[$table]=$columns;
}

// show field/row content
if( isset($_GET['showcontent']) && isset($_GET['t']) && isset($_GET['c']) && isset($_GET['id_name']) && isset($_GET['id']) ) {

    $table_content = mysql_real_escape_string( $_GET['t'] );
    $column_content = mysql_real_escape_string( $_GET['c'] );
    $id_name_content = mysql_real_escape_string( $_GET['id_name'] );
    $id_content = intval( $_GET['id'] );

    if(isset($_POST['updatecontent'])){
        if ( get_magic_quotes_gpc() )
        {
            $_POST['row_content'] = stripslashes( $_POST['row_content'] );
        }

        $sql_content = "SELECT * from $table_content WHERE $id_name_content=$id_content";
        $res_content = mysql_query($sql_content) or die("$sql_content -- ".mysql_error());

        $row = mysql_fetch_assoc($res_content);

        backupRow( $table_content, $row, "\nWHERE $id_name_content=$id_content" );

        $sql_content_update = "UPDATE `$table_content` set `$column_content` = '".mysql_real_escape_string(htmlspecialchars_decode($_POST['row_content'], ENT_COMPAT))."' where `$id_name_content`=$id_content";
        $restore_res_update=mysql_query($sql_content_update) or die(mysql_error());
        echo "\nUpdated ...\n";
    }

    $sql_content = "SELECT * from $table_content WHERE $id_name_content=$id_content";
    $res_content = mysql_query($sql_content) or die("$sql_content -- ".mysql_error());

    $row = mysql_fetch_assoc($res_content);

    echo "<form method=\"post\" name=\"update\" action=\"\">";
    echo "<input type=\"hidden\" name=\"updatecontent\" value=\"updatecontent\" />";

    echo "\nTableName: $table_content -> FieldName: $column_content -> ID: $id_content - <input type=\"submit\" class=\"greenbutton-small\" name=\"submit\" value=\"Update Content\" />\n";

    echo "\n<textarea id=\"row_content\" name=\"row_content\" style=\"margin: 2px; height: 95%; width: 100%;\">";

    echo htmlspecialchars($row[$column_content], ENT_COMPAT, 'ISO-8859-1', true);

    echo "</textarea>\n";
    echo "</form>";

    exit(1);
}
// search all tables

// we can have a whitelist tables list
if( isset($_GET['table']) ) {

    $list_tables = array();
    $m_table = explode(",", $_GET['table']);

    foreach ($m_table as $s_table) {
        $list_tables[] = $s_table;
    }
} else {
     $list_tables = array('posts', 'content', 'template');
}

function get_wp_config( $line )
{
    $var_detection = array(
        'DB_HOST' => array( 3, 'DBHOST' ),
        'DB_USER' => array( 3, 'DBUSER' ),
        'DB_PASSWORD' => array( 3, 'DBPASS' ),
        'DB_NAME' => array( 3, 'DBDB' ),
        '$tableprefix' => array( 1, 'DBPREFIX' ),
    );

    read_conf( $var_detection, $line );
}

function get_drupal_config( $line )
{
    $var_detection = array(
       "'database' =>" => array( 3, 'DBDB' ),
       "'username' =>" => array( 3, 'DBUSER'),
       "'password' =>" => array( 3, 'DBPASS' ),
       "'prefix' =>"   => array( 3, 'DBPREFIX' ),
       "'host' =>"     => array( 3, 'DBHOST' )
    );

    read_conf( $var_detection, $line );
}

function get_joomla_config( $line )
{
    $var_detection = array(
        'var $host' => array( 1, 'DBHOST' ),
        'var $user' => array( 1, 'DBUSER' ),
        'var $password' => array( 1, 'DBPASS' ),
        'var $db' => array( 1, 'DBDB' ),
        'var $dbprefix' => array( 1, 'DBPREFIX' ),
        'public $host' => array( 1, 'DBHOST' ),
        'public $user' => array( 1, 'DBUSER' ),
        'public $password' => array( 1, 'DBPASS' ),
        'public $db' => array( 1, 'DBDB' ),
        'public $dbprefix' => array( 1, 'DBPREFIX' ),
    );

    read_conf( $var_detection, $line );
}

function get_vbulletin_config( $line )
{
    global $DBHOST;

    $var_detection = array(
        "config['MasterServer']['servername']" => array( 5, 'DBHOST' ),
        "config['MasterServer']['username']" => array( 5, 'DBUSER' ),
        "config['MasterServer']['password']" => array( 5, 'DBPASS' ),
        "config['Database']['dbname']" => array( 5, 'DBDB' ),
    );

    read_conf( $var_detection, $line );

    if ( FALSE === strpos( $line, "config['MasterServer']['port']" ) )
    {
        return;
    }

    $line = trim($line);
    $line_exp = explode("'", $line);

    if( !isset( $line_exp[5] ) )
    {
        $line_exp = explode( '=', $line );

        if ( array_key_exists( 1, $line_exp ) )
        {
            $DBHOST .= ':' . trim($line_exp[1]);
        }
    }
    else
    {
        $DBHOST .= ':' . trim($line_exp[5]);
    }
}

function read_conf( $conf, $line )
{
    if ( 0 === strpos( ltrim( $line ), '//' ) )
    {
        return;
    }

    global $DBHOST;
    global $DBUSER;
    global $DBPASS;
    global $DBDB;
    global $DBPREFIX;

    foreach ( $conf as $line_sig => $info )
    {
        if ( FALSE === strpos( $line, $line_sig ) )
        {
            continue;
        }


        if ( preg_match( '/\$_ENV[{[\'\s]+([^\'}\]\s]+)[}\'\]\s]+/', $line, $matches ) )
        {
            $$info[1] = $_ENV{$matches[1]};
            break;
        }

        $line = trim($line);
        $line_exp = explode("'", $line);

        if( isset( $line_exp[$info[0]] ) )
        {
            $$info[1] = trim( $line_exp[$info[0]] );
            break;
        }
    }
}

function search_and_clean( $list_of_sigs, $clean_it=FALSE ) {

    global $all_tables_columns;
    global $list_tables;

    // whitelist tabel
    if( !isset($_GET['s']) && isset($_GET['whitelist']) ) {

        $whitelist_tables = array();
        foreach($list_tables as $w_table){
            foreach($all_tables_columns as $tableName=>$fieldArray){
                if( strpos($tableName, "$w_table") !== false ){
                    echo "whitelisted table : $tableName\n";
                    $whitelist_tables[$tableName] = $fieldArray;
                }
            }// end all_tables_columns loop
        }// end list_tables loop

        $all_tables_columns = $whitelist_tables;
    }

    foreach($all_tables_columns as $tableName=>$fieldArray){

        $table_key_name = $fieldArray[0][0];

        if( isset($_GET['noise']) ){
            @ob_start();
            echo "\nsearching table : $tableName .....\n";
            @ob_end_flush();
            @flush();
        }

        foreach($fieldArray as $fields) {
            $field=$fields[0];
            $type=$fields[1];
            $type=strtolower($type);
            $type=trim($type);

            // echo "searching in : $tableName : $fields[0] : $type\n";

            // search only rows that can have text in them
            if($type=="varchar" || $type=="char" || $type=="datetime" || $type == "mediumtext" ||$type=="text" || $type=="longtext"){
                $type="string";
            }

            if($type=="string"){

                // creat the SELECT whit all words at once
                $sql="SELECT * FROM `$tableName`";
                $sql_nr = 0;

                foreach($list_of_sigs as $sig => $sig_regex) {

                    if($sql_nr == 0){
                        $sql .= " WHERE `$field` like '%".mysql_real_escape_string($sig)."%'";
                    } else {
                         $sql .= " OR `$field` like '%".mysql_real_escape_string($sig)."%'";
                    }
                    $sql_nr++;

                }//end list_of_sigs

                // echo "searching in : $tableName : $fields[0] : $fields[1]\n";
                // echo $sql."\n\n";

                $res=mysql_query($sql) or die("$sql -- ".mysql_error());
                $num=mysql_num_rows($res);
                if($num>0){

                    while($row = mysql_fetch_assoc($res)){
                        @ob_start();
                        if($clean_it){

                            $cleared_row = $row[$field];

                        // regex cleanup
                            foreach( $list_of_sigs as $sig => $sig_regex ) {

                                if( $sig_regex == "spam_link"){

                                    $sig_regex = '/<a.*?href=["|\']?.*?http:.*'.$sig.'[^<]*<\/a>/i';

                                }
				// check first if the signature is present
				if(strpos($cleared_row, "$sig") !== FALSE) {
					if (preg_match('/<div\s*style..position.absolute;\s*left.-[0-9]{4,}px;\s*top.-[0-9]{4,}px.[^>]+>(<p>)?\w+[^<]+<a.*?href=["|\']?.*?http:.*'.$sig.'[^<]*<\/a>/', $cleared_row) !== FALSE) {
						$sig_regex = '/<div\s*style..position.absolute;\s*left.-[0-9]{4,}px;\s*top.-[0-9]{4,}px.[^>]+>(<p>)?\w+[^<]+<a.*?href=["|\']?.*?http:.*'.$sig.'[^<]*<\/a>(\s*\w+[^<]+<a href..http[^>]+>\s*\w+[^>]+<.a>)+(\s*\w+[^<]+)?(<.p>)?<.div>/i';

					}
                                	$regex_result = preg_replace($sig_regex,'',$cleared_row);
                                	// check if the regex was successfully
                                	if( strlen($regex_result) != strlen($cleared_row) ) {
                                    		$cleared_row = $regex_result;
                                	} else {
                                    		if( strpos($cleared_row, "$sig") !== FALSE ) {
                                    			echo "\nWARN: Found '".htmlspecialchars($sig, ENT_COMPAT, 'ISO-8859-1', true)."' in TableName: $tableName -> FieldName: $field -> ID: $row[$table_key_name] - <a href=\"?srun&showcontent&t=$tableName&c=$field&id_name=$table_key_name&id=$row[$table_key_name]\" target=_blank>show content</a>\n";
                                    		}
                                	}//end check if the regex was successfully
				} //end check if signature is present
                            }//end list_of_sigs loop

                            // check if any cleanup was done
                            if( $cleared_row != NULL && strlen($cleared_row) > 2 && (strlen($cleared_row) != strlen($row[$field])) ) {

                                // make a row backup
                                $update_backup = "UPDATE `$tableName` set `$field` = '".mysql_real_escape_string($row[$field])."' where `$table_key_name` = '".$row[$table_key_name]."'";
                                if ( !backupDBChange( $tableName, $update_backup ) )
                                {
                                    echo( '\nERROR: unable to create backup for table ' . htmlspecialchars( $tableName ) . " row \n" );
                                }
                                else
                                {
                                    $sql_cleared = "UPDATE `$tableName` set `$field` = '".mysql_real_escape_string($cleared_row)."' where `$table_key_name` = '".$row[$table_key_name]."'";
                                    $clean_res=mysql_query($sql_cleared) or die("$sql_cleared -- ".mysql_error());

                                    echo "\nCLEARED: TableName: $tableName -> FieldName: $field -> ID: $row[$table_key_name]\n";
                                }
                            }
                        // end regex cleanup

                        } else {

                            // no cleanup just search
                            foreach( $list_of_sigs as $sig => $sig_regex ) {
                                if( strpos($row[$field], "$sig") !== FALSE ) {
                                    echo "\nWARN: Found '".htmlspecialchars($sig, ENT_COMPAT, 'ISO-8859-1', true)."' in TableName: $tableName -> FieldName: $field -> ID: $row[$table_key_name] - <a href=\"?srun&showcontent&t=$tableName&c=$field&id_name=$table_key_name&id=$row[$table_key_name]\" target=_blank>show content</a>\n";
                                }
                             }//end list_of_sigs loop

                        } // end clean_it
                        @ob_end_flush();
                        @flush();
                    }// end mysql_fetch_assoc
                }//end num

            }//end type
        }//end fieldArray loop

    }// end all_tables_columns loop
}// end function

function search_base64()
{
    global $all_tables_columns;
    global $list_tables;

    $string_types = 'varchar*#*char*#*datetime*#*mediumtext*#*text*#*longtext';

    // whitelist table
    if ( !isset( $_GET['s'] ) && isset( $_GET['whitelist'] ) )
    {
        $whitelist_tables = array();

        foreach ( $list_tables as $w_table )
        {
            foreach ( $all_tables_columns as $tableName => $fieldArray )
            {
                if( strpos( $tableName, "$w_table" ) !== false )
                {
                    echo "whitelisted table : $tableName\n";
                    $whitelist_tables[$tableName] = $fieldArray;
                }
            }
        }

        $all_tables_columns = $whitelist_tables;
    }

    foreach ( $all_tables_columns as $tableName => $fieldArray )
    {

        $table_key_name = $fieldArray[0][0];

        if ( isset( $_GET['noise'] ) )
        {
            @ob_start();
            echo "\nsearching table : $tableName .....\n";
            @ob_end_flush();
            @flush();
        }

        foreach ( $fieldArray as $fields )
        {
            $field = $fields[0];
            $type = trim( strtolower( $fields[1] ) );

            // echo "searching in : $tableName : $fields[0] : $type\n";

            // search only rows that can have text in them
            if ( FALSE === strpos( $string_types, $type ) )
            {
                continue;
            }

            $sql = "SELECT * FROM `$tableName` WHERE `$field` REGEXP '[0-9A-Za-z\+\/\=]{200,}';";

            $res = mysql_query( $sql ) or die( "$sql -- " . mysql_error() );
            $num = mysql_num_rows( $res );

            if ( $num <= 0 )
            {
                continue;
            }

            while ( $row = mysql_fetch_assoc( $res ) )
            {
                @ob_start();
                echo "\nWARN: Found base64 content in TableName: "
                . " $tableName -> FieldName: $field -> ID: $row[$table_key_name]"
                . " - <a href=\"?srun&showcontent&t=$tableName&c=$field&id_name="
                . "$table_key_name&id=$row[$table_key_name]\" target=_blank>show content</a>\n";
            }

            @ob_end_flush();
            @flush();
        }
    }
}

function deleteWPRows()
{
    global $all_tables, $list_of_option_rows;

    $tables = array_filter( $all_tables, 'getOptionsTables' );

    if ( !is_array( $tables ) || 0 == count( $tables ) )
    {
        return;
    }

    foreach ( $tables as $table )
    {

        $sql = "SELECT * FROM $table WHERE option_name IN ( '" . implode( "','", $list_of_option_rows ) . "' )";
        $res = mysql_query( $sql );

        if ( !$res )
        {
            continue;
        }

        $num = mysql_num_rows( $res );

        if ( 0 == $num )
        {
            continue;
        }

        while ( $row = mysql_fetch_assoc( $res ) )
        {
            echo "\nOK: Removed row from TableName: $table -> FieldName: option_name -> ID: {$row['option_name']}\n";
            backupRow( $table, $row, "\nWHERE option_name={$row['option_name']}" );
            $sql = "DELETE FROM $table WHERE option_name = '" . $row['option_name'] . "'";
            mysql_query( $sql ) or die( "$sql -- " . mysql_error() );
        }
    }

}

function deleteWPAdmin()
{
    global $DBPREFIX;

    $sql = "SELECT * FROM {$DBPREFIX}users WHERE ID = 1001001";
    $res = mysql_query( $sql );

    if ( !$res )
    {
        return;
    }

    $num = mysql_num_rows( $res );

    if ( 0 == $num )
    {
        return;
    }

    while ( $row = mysql_fetch_assoc( $res ) )
    {
        echo "\nOK: Removed malicious admin from TableName: {$DBPREFIX}users -> FieldName: ID -> ID: 1001001\n";
        backupRow( "{$DBPREFIX}users", $row, "\nWHERE ID = 1001001" );
        $sql = "DELETE FROM {$DBPREFIX}users WHERE ID = 1001001";
        mysql_query( $sql ) or die( "$sql -- " . mysql_error() );
    }
}

function checkWPDefaultUserRole()
{
    global $all_tables;

    $tables = array_filter( $all_tables, 'getOptionsTables' );

    if ( !is_array( $tables ) || 0 == count( $tables ) )
    {
        return;
    }

    foreach ( $tables as $table )
    {

        $sql = "SELECT * FROM $table WHERE option_name LIKE 'default_role' AND option_value NOT LIKE 'subscriber'";
        $res = mysql_query( $sql );

        if ( !$res )
        {
            continue;
        }

        $num = mysql_num_rows( $res );

        if ( 0 == $num )
        {
            continue;
        }

        while ( $row = mysql_fetch_assoc( $res ) )
        {
            echo "\nWARN: Default Wordpress user role not set to 'subscriber' in table $table, please notify the client to change this for security reasons.\n";
        }
    }
}

function backupRow( $table, $row, $where )
{
    $sql = "UPDATE $table SET";
    foreach ( $row as $key => $value )
    {
        $sql .= " $key = '$value',";
    }

    $sql = trim( $sql, ',' );
    $sql .= " $where";

    return backupDBChange( $table, $sql );
}

function getOptionsTables( $table )
{
    return false !== strpos( $table, '_options');
}

function backupDBChange( $table, $change ) {
    $filename = $table;
    $appendix = BACKUP_APPENDIX.time();

    //check for quaranteen folder
    if ( !create_quarantine_dir() )
    {
        return( 0 );
    }

    //encrypt the file and save in that folder
    $backupFile = QUARANTINE_FOLDER . DS . $filename . $appendix;

    $fp = @fopen($backupFile, "w");
    if(!$fp) {//if cannot create file, fail
        return(0);
    }

    fwrite( $fp, encrypt( $change, SUCURI_KEY ) );
    fclose( $fp );

    return( $backupFile );
}

function encrypt($content, $key) {
    if (!$key) {
        return(0);
    }
    $result = '';

    $contentLength = strlen($content);
    $keyLength = strlen($key);

    $restLenght = $contentLength % $keyLength;
    $firstPartLenght = $contentLength - $restLenght;

    for ($i = 0; $i <$firstPartLenght; $i+=$keyLength) {
        $part = substr($content, $i, $keyLength);
        $result .= "$key" ^ "$part";
    }

    if ($restLenght) {
        $part = substr($content, $firstPartLenght, $restLenght);
        $partKey = substr($key, 0, $restLenght);
        $result .= "$part" ^ "$partKey";
    }
    return($result);
}

function create_directory( $directory )
{
    if ( !is_dir( $directory ) ) //if it doesn't exist, create it
    {
        if( !@mkdir( $directory, 0755, true ) ) //if cannot create, fail
        {
            return false;
        }
    }

    return true;
}

function create_quarantine_dir()
{
    if ( !create_directory( QUARANTINE_FOLDER ) )
    {
        return false;
    }

    @touch( QUARANTINE_FOLDER . '/index.html' );
    @touch( QUARANTINE_FOLDER . '/index.php' );
    @file_put_contents( QUARANTINE_FOLDER . '/.htaccess', 'deny from all' );

    return true;
}

function get_all_backup_files()
{
    $handle = @opendir( QUARANTINE_FOLDER );
    $files = array();

    if ( !$handle )
    {
        return $files;
    }

    while ( false !== ( $file = readdir( $handle ) ) )
    {
        if ( $file == "."
            || $file == ".."
            || is_dir( $file )
            || FALSE === strpos( $file, BACKUP_APPENDIX ) )
        {
            continue;
        }

        if ( isset( $_GET['date'] ) )
        {
            $key = explode( BACKUP_APPENDIX, $file );
            $key = $key[1];

            if ( $key > $_GET['date'] || $key < $_GET['date'] - ( 24 * 60 * 60 ) )
            {
                continue;
            }
        }

        $files[] = QUARANTINE_FOLDER . '/'.  $file;
    }

    rsort( $files );
    return $files;
}

function restore_backup( $file )
{
    if ( !strpos( $file, BACKUP_APPENDIX ) )
    {
        return( 0 );
    }

    $file_contents = file_get_contents( $file );
    $file_contents = encrypt( $file_contents, SUCURI_KEY );

    $table_name = explode( BACKUP_APPENDIX, $file );
    $table_name = $table_name[0];
    $table_name = explode( QUARANTINE_FOLDER, $table_name );
    $table_name = $table_name[1];
    $table_name = ltrim( $table_name, './' );

    $where = preg_match( '/WHERE.*/i', $file_contents, $matches );

    if ( !$where )
    {
        return( 0 );
    }

    $where = $matches[0];

    $sql_content = "SELECT * from $table_name $where";
    $res_content = mysql_query($sql_content) or die("$sql_content -- ".mysql_error());

    $row = mysql_fetch_assoc($res_content);

    $backupcopy = backupRow( $table_name, $row, $where );

    if ( !$backupcopy ) {
        echo( 'ERROR: unable to create backup for table ' . htmlspecialchars( $table_name ) . " row \n" );
        return( 0 );
    }

    //restore DB
    $res_content = mysql_query( $file_contents ) or die("$sql_content -- ".mysql_error());

    return(1);
}

if ( isset( $_GET['base64'] ) )
{
    search_base64();

    echo "\nINFO: Completed\n";
    echo "</pre>";

    mysql_close( $link );
    exit(0);

}

if( isset($_GET['s']) ){

    $sig = $_GET['s'];
    $sigs = array($sig => 'search_only' );

    search_and_clean($sigs, FALSE);

} elseif( !isset($_GET['clean']) ) {
    search_and_clean($list_of_spam_links, FALSE);
    search_and_clean($list_of_regex, FALSE);
    search_and_clean($list_of_search, FALSE);
} else {
    search_and_clean($list_of_spam_links, TRUE);
    search_and_clean($list_of_regex, TRUE);
}

if ( 'Wordpress' == $CMS )
{
    deleteWPRows();
    deleteWPAdmin();
    checkWPDefaultUserRole();
}

echo "\nINFO: Completed\n";
echo "</pre>";

mysql_close($link);
exit(0);

?>

